import { useEffect, useRef, useState } from "react";
import { GuidedSpeakingRenderer, MeaningSelectRenderer, SentenceBuildRenderer, TypedRecallRenderer } from "../activities/registry";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.classroom-survival";
const steps = ["Warm-up", "Meet", "Choose", "Listen", "Build", "Use", "Check", "Complete"];
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;
const p = { no: "Je ne comprends pas.", repeat: "Pouvez-vous répéter, s’il vous plaît ?", slow: "Plus lentement, s’il vous plaît.", mean: "Qu’est-ce que ça veut dire ?", say: "Comment dit-on … en français ?", yes: "Je comprends." };

function Choice({ id, prompt, options, answer, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; onComplete: Complete }) {
  return <MeaningSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} prompt={prompt} options={options} answer={answer} feedback={{ [answer]: `${answer} matches the help needed.` }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} />;
}

export default function ClassroomSurvivalLesson() {
  const learner = useGuestLearner(lessonId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [step, setStep] = useState(0); const [furthest, setFurthest] = useState(0); const [done, setDone] = useState<Set<string>>(new Set()); const [transcript, setTranscript] = useState(false); const [exit, setExit] = useState<Record<string, boolean>>({}); const [round, setRound] = useState(1); const [saveError, setSaveError] = useState<string>();
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current = true; const saved = Math.min(learner.progress?.currentStep ?? 0, 7); setStep(saved); setFurthest(Math.min(learner.progress?.furthestStep ?? saved, 7)); } }, [learner.loading, learner.progress]);
  useEffect(() => { headingRef.current?.focus(); }, [step]);
  useEffect(() => () => { if (sessionId.current) void learner.repository.endSession(sessionId.current); }, [learner.repository]);
  const complete: Complete = async (itemId, response, correct) => { if (correct) setDone(current => new Set(current).add(itemId)); if (!learner.enrollment) return; try { if (!sessionId.current) sessionId.current = (await learner.repository.startSession(lessonId, "deep_link")).id; await learner.repository.submitAttempt({ learnerId: learner.enrollment.learnerId, enrollmentId: learner.enrollment.id, sessionId: sessionId.current, lessonId, activityId: itemId.replace("item", "activity").replace(/\.\w+$/, ""), itemId, response, correct, idempotencyKey: crypto.randomUUID() }); await learner.refresh(); setSaveError(undefined); } catch { setSaveError("Progress could not be saved. You can continue this session."); } };
  const exitComplete: Complete = async (id, response, correct) => { setExit(current => ({ ...current, [id]: correct })); await complete(id, response, correct); };
  const move = async (next: number) => { setStep(next); setFurthest(current => Math.max(current, next)); if (learner.enrollment) { try { await learner.repository.saveLessonPosition(lessonId, next); await learner.refresh(); } catch { setSaveError("Your lesson position could not be saved."); } } };
  const has = (...ids: string[]) => ids.every(id => done.has(id));
  const requirements = [has("item.a1.u01.l05.warmup.1", "item.a1.u01.l05.warmup.2"), has("item.a1.u01.l05.notice"), [1,2,3,4,5,6].every(n => done.has(`item.a1.u01.l05.meaning.${n}`)), has("item.a1.u01.l05.listen.1", "item.a1.u01.l05.listen.2", "item.a1.u01.l05.listen.3"), has("item.a1.u01.l05.build.1", "item.a1.u01.l05.build.2", "item.a1.u01.l05.recall"), has("item.a1.u01.l05.role.1", "item.a1.u01.l05.role.2", "item.a1.u01.l05.role.3"), false, false];
  const check = async () => { if (Object.keys(exit).length === 4 && Object.values(exit).filter(Boolean).length >= 3 && exit["item.a1.u01.l05.exit.sequence"]) { if (learner.enrollment) await learner.repository.completeLesson(lessonId); await move(7); } };
  if (learner.loading) return <p role="status">Loading Lesson 5…</p>;
  const dialogue = [["Morgan", "Écoutez et répétez.", "Listen and repeat."], ["Alex", "Pardon. Je ne comprends pas.", "Sorry. I don't understand."], ["Alex", "Pouvez-vous répéter, s’il vous plaît ?", "Can you repeat, please?"], ["Morgan", "Oui. Écoutez… et répétez.", "Yes. Listen… and repeat."], ["Alex", "Plus lentement, s’il vous plaît.", "More slowly, please."], ["Morgan", "Bien sûr.", "Of course."], ["Alex", "Merci. Je comprends.", "Thank you. I understand."]];
  return <article className="lesson-flow lesson-player classroom-survival-lesson">
    <header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Lesson 5 · {steps[step]}</p><h1>Classroom survival</h1><p className="page-sub">I can ask for repetition, clarification, or slower speech.</p><Progress label="Lesson progress" value={step} max={7} /><ol className="lesson-stepper" aria-label="Lesson steps">{steps.map((label, index) => <li key={label} className={index === step ? "is-current" : index < step ? "is-done" : ""}><span>{index + 1}</span>{label}</li>)}</ol>{saveError && <Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>
    {step === 0 && <section className="lesson-stage lesson-two-warmup"><div className="lesson-stage-intro"><p className="learn-preview-kicker">1 · Quick retrieval</p><h2 ref={headingRef} tabIndex={-1}>Start politely</h2><p>Use Lesson 4 courtesy before asking someone to change how they speak.</p></div><div className="contrast-grid"><Choice id="item.a1.u01.l05.warmup.1" prompt="You interrupt politely." options={["Excusez-moi.", "De rien."]} answer="Excusez-moi." onComplete={complete} /><Choice id="item.a1.u01.l05.warmup.2" prompt="You make a polite request." options={["S’il vous plaît.", "Merci beaucoup."]} answer="S’il vous plaît." onComplete={complete} /></div></section>}
    {step === 1 && <section className="lesson-stage lesson-scene lesson-two-scene"><img src="/images/course/a1/unit-01/classroom-repair-v1.png" alt="Alex asks for clarification while Morgan responds supportively in a bright language-school classroom." /><div className="lesson-scene__copy"><div className="lesson-stage-intro"><p className="learn-preview-kicker">2 · Meet Alex and Morgan</p><h2 ref={headingRef} tabIndex={-1}>It is okay to stop and ask</h2><p>Morgan speaks too quickly. Alex uses repair phrases to keep the conversation going.</p></div><AudioControl label="Play Alex and Morgan's dialogue" onPlay={() => speak(dialogue.map(line => line[1]).join(" "))} onPlaySlow={() => speak(dialogue.map(line => line[1]).join(" "), { rate: 0.75 })} /><Choice id="item.a1.u01.l05.notice" prompt="How does Alex solve the problem?" options={["He asks Morgan to repeat more slowly", "He leaves", "He spells his name"]} answer="He asks Morgan to repeat more slowly" onComplete={complete} /><Button variant="secondary" onClick={() => setTranscript(value => !value)}>{transcript ? "Hide transcript" : "Show transcript"}</Button>{transcript && <div className="dialogue">{dialogue.map(([speaker, french, english]) => <div key={`${speaker}-${french}`}><strong>{speaker}</strong><span><b lang="fr">{french}</b><small>{english}</small></span><AudioControl label={`Play ${speaker}'s line`} onPlay={() => speak(french)} onPlaySlow={() => speak(french, { rate: 0.75 })} /></div>)}</div>}<Card title="A communication skill"><p>Not understanding is normal. A repair phrase tells the other person exactly how to help.</p></Card></div></section>}
    {step === 2 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">3 · Choose a strategy</p><h2 ref={headingRef} tabIndex={-1}>Match each problem to a useful tool</h2></div><div className="phrase-guide">{[[p.no,"I don't understand"],[p.repeat,"Please repeat"],[p.slow,"Speak more slowly"],[p.mean,"What does it mean?"],[p.say,"How do you say it?"],[p.yes,"I understand now"]].map(([fr,en]) => <button key={fr} onClick={() => speak(fr)}><span>🔊</span><strong>{fr}</strong><small>{en}</small></button>)}</div><div className="activity-stack"><Choice id="item.a1.u01.l05.meaning.1" prompt="You did not understand." options={[p.no,p.yes]} answer={p.no} onComplete={complete}/><Choice id="item.a1.u01.l05.meaning.2" prompt="You want to hear it again." options={[p.repeat,p.slow]} answer={p.repeat} onComplete={complete}/><Choice id="item.a1.u01.l05.meaning.3" prompt="The speaker is too fast." options={[p.slow,p.mean]} answer={p.slow} onComplete={complete}/><Choice id="item.a1.u01.l05.meaning.4" prompt="You need a word's meaning." options={[p.mean,p.say]} answer={p.mean} onComplete={complete}/><Choice id="item.a1.u01.l05.meaning.5" prompt="You need the French word for ‘book’." options={["Comment dit-on “book” en français ?",p.repeat]} answer="Comment dit-on “book” en français ?" onComplete={complete}/><Choice id="item.a1.u01.l05.meaning.6" prompt="You understand now." options={[p.yes,p.no]} answer={p.yes} onComplete={complete}/></div></section>}
    {step === 3 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">4 · Listen for the need</p><h2 ref={headingRef} tabIndex={-1}>Unknown words are not the test</h2><p>The repair phrase reveals what help the learner needs.</p></div><div className="activity-stack"><div className="listening-activity"><AudioControl label="Play fast-course dialogue" onPlay={() => speak("Le cours commence à neuf heures. Plus lentement, s'il vous plaît.")} onPlaySlow={() => speak("Le cours commence à neuf heures. Plus lentement, s'il vous plaît.", {rate: .75})}/><Choice id="item.a1.u01.l05.listen.1" prompt="What does Alex need?" options={["Slower speech","A translation","A name"]} answer="Slower speech" onComplete={complete}/></div><div className="listening-activity"><AudioControl label="Play unknown-word dialogue" onPlay={() => speak("Ouvrez le document. Qu'est-ce que ouvrez veut dire ?")}/><Choice id="item.a1.u01.l05.listen.2" prompt="What does Alex need?" options={["The meaning of a word","Slower speech","A farewell"]} answer="The meaning of a word" onComplete={complete}/></div><div className="listening-activity"><AudioControl label="Play classroom-number dialogue" onPlay={() => speak("Votre cours est dans la salle douze. Pouvez-vous répéter, s'il vous plaît ?")}/><Choice id="item.a1.u01.l05.listen.3" prompt="What will Morgan probably do?" options={["Repeat the information","End class","Spell Alex"]} answer="Repeat the information" onComplete={complete}/></div></div></section>}
    {step === 4 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">5 · Build and recall</p><h2 ref={headingRef} tabIndex={-1}>Make the repair phrases complete</h2></div><div className="activity-stack"><SentenceBuildRenderer activityId="activity.a1.u01.l05.build" itemId="item.a1.u01.l05.build.1" prompt="Build ‘I don’t understand.’" tokens={["pas",".","Je","ne comprends"]} answer="Je ne comprends pas ." onSubmit={({envelope,evaluation}) => complete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/><SentenceBuildRenderer activityId="activity.a1.u01.l05.build" itemId="item.a1.u01.l05.build.2" prompt="Build the polite repetition request." tokens={["s’il vous plaît","répéter","?","Pouvez-vous",","]} answer="Pouvez-vous répéter , s’il vous plaît ?" onSubmit={({envelope,evaluation}) => complete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/><TypedRecallRenderer activityId="activity.a1.u01.l05.recall" itemId="item.a1.u01.l05.recall" prompt="Type ‘What does that mean?’ in French." answers={[p.mean,"Qu'est-ce que ça veut dire ?"]} policy={{accents:"forgiving",punctuation:"optional"}} onSubmit={({envelope,evaluation}) => complete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/></div></section>}
    {step === 5 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">6 · Repair the conversation</p><h2 ref={headingRef} tabIndex={-1}>Help Alex keep going</h2><p>Speaking afterward is optional.</p></div><div className="activity-stack"><Choice id="item.a1.u01.l05.role.1" prompt="Morgan speaks too quickly." options={[p.slow,p.yes,p.say]} answer={p.slow} onComplete={complete}/><Choice id="item.a1.u01.l05.role.2" prompt="Morgan repeats and Alex understands." options={[p.yes,p.no,p.repeat]} answer={p.yes} onComplete={complete}/><Choice id="item.a1.u01.l05.role.3" prompt="Morgan uses an unknown word." options={[p.mean,p.slow,p.yes]} answer={p.mean} onComplete={complete}/></div><aside className="role-play"><strong>Optional speaking</strong><GuidedSpeakingRenderer activityId="activity.a1.u01.l05.speaking" itemId="item.a1.u01.l05.speaking" prompt="Ask for slower speech, then confirm understanding." model="Plus lentement, s'il vous plaît. Merci. Je comprends." onSubmit={({envelope,evaluation}) => complete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/></aside></section>}
    {step === 6 && <section className="lesson-stage lesson-check" key={round}><p className="learn-preview-kicker">7 · Check</p><h2 ref={headingRef} tabIndex={-1}>Can you repair an interaction without hints?</h2><p>Pass 3 of 4, including the two-part response.</p><Choice id="item.a1.u01.l05.exit.slow" prompt="The speaker is too fast." options={[p.slow,p.repeat,p.yes]} answer={p.slow} onComplete={exitComplete}/><TypedRecallRenderer activityId="activity.a1.u01.l05.exit" itemId="item.a1.u01.l05.exit.typed" prompt="Type ‘I don’t understand.’ in French." answers={[p.no]} policy={{accents:"forgiving",punctuation:"optional"}} onSubmit={({envelope,evaluation}) => exitComplete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/><SentenceBuildRenderer activityId="activity.a1.u01.l05.exit" itemId="item.a1.u01.l05.exit.repeat" prompt="Build the polite repetition request." tokens={["répéter","s’il vous plaît","Pouvez-vous","?",","]} answer="Pouvez-vous répéter , s’il vous plaît ?" onSubmit={({envelope,evaluation}) => exitComplete(envelope.itemId,String(envelope.response),evaluation.outcome === "correct")}/><Choice id="item.a1.u01.l05.exit.sequence" prompt="Morgan speaks too quickly, then repeats. Choose Alex's two responses." options={["Plus lentement, s’il vous plaît. — Merci. Je comprends.","Je comprends. — Plus lentement, s’il vous plaît.","De rien. — Je ne comprends pas."]} answer="Plus lentement, s’il vous plaît. — Merci. Je comprends." onComplete={exitComplete}/>{Object.keys(exit).length === 4 && <Button onClick={() => void check()}>Check my lesson result</Button>}{Object.keys(exit).length === 4 && !(Object.values(exit).filter(Boolean).length >= 3 && exit["item.a1.u01.l05.exit.sequence"]) && <div className="remediation"><Feedback title="Review and retry" tone="error">Ask for the exact help you need, then confirm when communication works.</Feedback><Button onClick={() => {setRound(value => value + 1);setExit({});}}>Retry lesson check</Button></div>}</section>}
    {step === 7 && <section className="lesson-stage lesson-summary"><p className="lesson-celebration">✓</p><p className="learn-preview-kicker">Lesson complete</p><h2 ref={headingRef} tabIndex={-1}>You can keep a difficult conversation going</h2><p>You can ask for repetition, slower speech, or meaning and confirm understanding.</p><div className="lesson-inline-actions"><Button onClick={() => void move(0)}>Practise again</Button><Link to="/learn/a1/unit/first-contact">Next: Unit 1 review →</Link></div></section>}
    {step < 7 && <nav className="lesson-navigation" aria-label="Lesson navigation">{step > 0 ? <Button variant="secondary" onClick={() => void move(step - 1)}>← Previous</Button> : <span/>}{step < 6 && <Button disabled={step >= furthest && !requirements[step]} onClick={() => void move(step + 1)}>Continue to {steps[step + 1]} →</Button>}</nav>}
  </article>;
}
