import { useEffect, useRef, useState } from "react";
import { AudioTextSelectRenderer, GuidedSpeakingRenderer, MeaningSelectRenderer } from "../activities/registry";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.sound-map";
const steps = ["Warm-up", "Meet", "Oral vowels", "Nasal vowels", "French R", "Speak", "Check", "Complete"];
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;

function Choice({ id, prompt, options, answer, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; onComplete: Complete }) {
  return <MeaningSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} prompt={prompt} options={options} answer={answer} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} />;
}

function SoundChoice({ id, audio, options, answer, note, assessment = false, onComplete }: { id: string; audio: string; options: readonly string[]; answer: string; note?: string; assessment?: boolean; onComplete: Complete }) {
  return <div className="listening-activity"><strong>Which word do you hear?</strong>{note && <p className="lesson-audio-hint">{note}</p>}<AudioTextSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} audio={audio} options={options} answer={answer} assessment={assessment} feedback={{ [answer]: `Yes—Camille says ${answer}.` }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} /></div>;
}

export default function CoreSoundMapLesson() {
  const learner = useGuestLearner(lessonId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [step, setStep] = useState(0); const [furthestStep, setFurthestStep] = useState(0); const [completed, setCompleted] = useState<Set<string>>(new Set()); const [transcript, setTranscript] = useState(false); const [exit, setExit] = useState<Record<string, boolean>>({}); const [round, setRound] = useState(1); const [saveError, setSaveError] = useState<string>();
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current = true; const saved = Math.min(learner.progress?.currentStep ?? 0, 7); setStep(saved); setFurthestStep(Math.min(learner.progress?.furthestStep ?? saved, 7)); } }, [learner.loading, learner.progress]);
  useEffect(() => { headingRef.current?.focus(); }, [step]);
  useEffect(() => () => { if (sessionId.current) void learner.repository.endSession(sessionId.current); }, [learner.repository]);
  const complete: Complete = async (itemId, response, correct) => { if (correct) setCompleted(current => new Set(current).add(itemId)); if (!learner.enrollment) return; try { if (!sessionId.current) sessionId.current = (await learner.repository.startSession(lessonId, "deep_link")).id; await learner.repository.submitAttempt({ learnerId: learner.enrollment.learnerId, enrollmentId: learner.enrollment.id, sessionId: sessionId.current, lessonId, activityId: itemId.replace("item", "activity").replace(/\.\w+$/, ""), itemId, response, correct, idempotencyKey: crypto.randomUUID() }); await learner.refresh(); setSaveError(undefined); } catch { setSaveError("Progress could not be saved. You can continue this session."); } };
  const exitComplete: Complete = async (id, response, correct) => { setExit(current => ({ ...current, [id]: correct })); await complete(id, response, correct); };
  const move = async (next: number) => { setStep(next); setFurthestStep(current => Math.max(current, next)); if (learner.enrollment) { try { await learner.repository.saveLessonPosition(lessonId, next); await learner.refresh(); } catch { setSaveError("Your lesson position could not be saved."); } } };
  const requirements = [completed.has("item.a1.u01.l03.warmup.g") && completed.has("item.a1.u01.l03.warmup.u"), completed.has("item.a1.u01.l03.notice"), ["rue", "roue", "été", "était"].every(word => completed.has(`item.a1.u01.l03.oral.${word}`)), ["sans", "son", "sain"].every(word => completed.has(`item.a1.u01.l03.nasal.${word}`)), completed.has("item.a1.u01.l03.r.merci") && completed.has("item.a1.u01.l03.r.revoir"), true, false, false];
  const check = async () => { const values = Object.values(exit); if (values.length === 5 && values.filter(Boolean).length >= 4) { if (learner.enrollment) await learner.repository.completeLesson(lessonId); await move(7); } };
  if (learner.loading) return <p role="status">Loading Lesson 3…</p>;
  return <article className="lesson-flow lesson-player sound-map-lesson">
    <header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Lesson 3 · {steps[step]}</p><h1>Core sound map</h1><p className="page-sub">I can hear several important French sound contrasts and try them clearly.</p><Progress label="Lesson progress" value={step} max={7} /><ol className="lesson-stepper" aria-label="Lesson steps">{steps.map((label, index) => <li key={label} className={index === step ? "is-current" : index < step ? "is-done" : ""}><span>{index + 1}</span>{label}</li>)}</ol>{saveError && <Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>

    {step === 0 && <section className="lesson-stage lesson-two-warmup"><div className="lesson-stage-intro"><p className="learn-preview-kicker">1 · Quick retrieval</p><h2 ref={headingRef} tabIndex={-1}>Warm up your French ear</h2><p>Bring back two letter sounds from Lesson 2 before listening inside words.</p></div><div className="contrast-grid"><SoundChoice id="item.a1.u01.l03.warmup.g" audio="G" options={["G", "J"]} answer="G" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.warmup.u" audio="U" options={["Q", "U"]} answer="U" onComplete={complete} /></div></section>}

    {step === 1 && <section className="lesson-stage lesson-scene lesson-two-scene"><img src="/images/course/a1/unit-01/core-sound-workshop-v2.png" alt="Camille models a French mouth shape while Maya listens and mirrors it in a bright language-school classroom." /><div className="lesson-scene__copy"><div className="lesson-stage-intro"><p className="learn-preview-kicker">2 · Meet Camille and Maya</p><h2 ref={headingRef} tabIndex={-1}>A pronunciation workshop</h2><p>Camille models two similar words. Maya listens for the sound that changes.</p></div><AudioControl label="Play Camille and Maya's dialogue" onPlay={() => speak("Écoute : rue, roue. Rue, roue. J'entends la différence.")} onPlaySlow={() => speak("Écoute : rue, roue. Rue, roue. J'entends la différence.", { rate: 0.75 })} /><Choice id="item.a1.u01.l03.notice" prompt="What is Maya listening for?" options={["A changing vowel sound", "A person's name", "A farewell"]} answer="A changing vowel sound" onComplete={complete} /><div className="lesson-inline-actions"><Button variant="secondary" onClick={() => setTranscript(value => !value)}>{transcript ? "Hide transcript" : "Show transcript"}</Button></div>{transcript && <div className="dialogue"><div><strong>Camille</strong><span><b lang="fr">Écoute : rue, roue. Rue, roue.</b><small>Listen: street, wheel. Street, wheel.</small></span><AudioControl label="Play Camille's line" onPlay={() => speak("Écoute : rue, roue. Rue, roue.")} onPlaySlow={() => speak("Écoute : rue, roue. Rue, roue.", { rate: 0.75 })} /></div><div><strong>Maya</strong><span><b lang="fr">J’entends la différence.</b><small>I hear the difference.</small></span><AudioControl label="Play Maya's line" onPlay={() => speak("J'entends la différence.")} onPlaySlow={() => speak("J'entends la différence.", { rate: 0.75 })} /></div></div>}<Card title="Listen before explaining"><p>You do not need phonetic symbols. First train your ear to notice that changing one sound can change the word.</p></Card></div></section>}

    {step === 2 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">3 · Oral vowels</p><h2 ref={headingRef} tabIndex={-1}>Hear <em>u/ou</em> and <em>é/è</em></h2><p><strong>u</strong> uses rounded lips with the tongue forward; <strong>ou</strong> is closer to English “oo.” For <strong>é</strong>, the mouth is more closed than for <strong>è</strong>.</p></div><div className="phrase-contrast"><span><strong lang="fr">rue / roue</strong><small>street / wheel</small></span><span><strong lang="fr">été / était</strong><small>summer / was</small></span></div><div className="activity-stack"><SoundChoice id="item.a1.u01.l03.oral.rue" audio="rue" options={["rue", "roue"]} answer="rue" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.oral.roue" audio="roue" options={["rue", "roue"]} answer="roue" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.oral.été" audio="été" options={["été", "était"]} answer="été" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.oral.était" audio="était" options={["été", "était"]} answer="était" onComplete={complete} /></div></section>}

    {step === 3 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">4 · Nasal vowels</p><h2 ref={headingRef} tabIndex={-1}>Let the vowel resonate</h2><p>In these sounds, air also passes through the nose. Do not pronounce a strong final <em>n</em>. Listen for the vowel quality in each word.</p></div><div className="phrase-guide sound-guide">{[["sans", "without · an sound"], ["son", "his/her · on sound"], ["sain", "healthy · in sound"]].map(([word, meaning]) => <button key={word} onClick={() => speak(word)}><span aria-hidden="true">🔊</span><strong lang="fr">{word}</strong><small>{meaning}</small></button>)}</div><div className="activity-stack"><SoundChoice id="item.a1.u01.l03.nasal.sans" audio="sans" options={["sans", "son", "sain"]} answer="sans" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.nasal.son" audio="son" options={["sans", "son", "sain"]} answer="son" onComplete={complete} /><SoundChoice id="item.a1.u01.l03.nasal.sain" audio="sain" options={["sans", "son", "sain"]} answer="sain" onComplete={complete} /></div></section>}

    {step === 4 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">5 · French R</p><h2 ref={headingRef} tabIndex={-1}>A gentle sound at the back of the mouth</h2><p>French <strong>r</strong> is usually formed toward the back of the mouth. Keep it light: clarity matters more than forcing a dramatic sound.</p></div><div className="summary-grid"><Card title="merci"><AudioControl label="Play merci" onPlay={() => speak("merci")} onPlaySlow={() => speak("merci", { rate: 0.7 })} /><p>The <strong>r</strong> sits between two vowels.</p></Card><Card title="au revoir"><AudioControl label="Play au revoir" onPlay={() => speak("au revoir")} onPlaySlow={() => speak("au revoir", { rate: 0.7 })} /><p>Keep both <strong>r</strong> sounds relaxed.</p></Card></div><div className="activity-stack"><SoundChoice id="item.a1.u01.l03.r.merci" audio="merci" options={["merci", "maisi"]} answer="merci" note="Choose the real French word." onComplete={complete} /><SoundChoice id="item.a1.u01.l03.r.revoir" audio="au revoir" options={["au revoir", "au vouar"]} answer="au revoir" note="Choose the familiar farewell." onComplete={complete} /></div></section>}

    {step === 5 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">6 · Optional speaking</p><h2 ref={headingRef} tabIndex={-1}>Try the sounds—or continue when ready</h2><p>Speaking is useful, but optional. Listen, repeat, and use the self-check only if you want active pronunciation practice.</p></div><div className="activity-stack"><GuidedSpeakingRenderer activityId="activity.a1.u01.l03.speak.merci" itemId="item.a1.u01.l03.speak.merci" prompt="Say: Merci beaucoup. Au revoir." model="Merci beaucoup. Au revoir." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /><GuidedSpeakingRenderer activityId="activity.a1.u01.l03.speak.contrast" itemId="item.a1.u01.l03.speak.contrast" prompt="Say slowly: rue, roue, rue, roue." model="Rue, roue, rue, roue." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /></div><Feedback title="A useful target" tone="info">Aim for a noticeable contrast—not a perfect accent. You can revisit this practice at any time.</Feedback></section>}

    {step === 6 && <section className="lesson-stage lesson-check" key={round}><p className="learn-preview-kicker">7 · Check</p><h2 ref={headingRef} tabIndex={-1}>Can you distinguish the sounds?</h2><p>Pass 4 of 5. You may retry every item after a wrong answer.</p><SoundChoice id="item.a1.u01.l03.exit.rue" audio="rue" options={["rue", "roue"]} answer="rue" assessment onComplete={exitComplete} /><SoundChoice id="item.a1.u01.l03.exit.roue" audio="roue" options={["rue", "roue"]} answer="roue" assessment onComplete={exitComplete} /><SoundChoice id="item.a1.u01.l03.exit.ete" audio="été" options={["été", "était"]} answer="été" assessment onComplete={exitComplete} /><SoundChoice id="item.a1.u01.l03.exit.son" audio="son" options={["sans", "son", "sain"]} answer="son" assessment onComplete={exitComplete} /><SoundChoice id="item.a1.u01.l03.exit.revoir" audio="au revoir" options={["merci", "au revoir"]} answer="au revoir" assessment onComplete={exitComplete} />{Object.keys(exit).length === 5 && <Button onClick={() => void check()}>Check my lesson result</Button>}{Object.keys(exit).length === 5 && Object.values(exit).filter(Boolean).length < 4 && <div className="remediation"><Feedback title="Listen once more" tone="error">Compare one pair at a time. Focus only on the changing sound, then retry.</Feedback><Button onClick={() => { setRound(value => value + 1); setExit({}); }}>Retry lesson check</Button></div>}</section>}

    {step === 7 && <section className="lesson-stage lesson-summary"><p className="lesson-celebration" aria-hidden="true">✓</p><p className="learn-preview-kicker">Lesson complete</p><h2 ref={headingRef} tabIndex={-1}>You can hear key French sound contrasts</h2><p>You distinguished <strong>u/ou</strong>, <strong>é/è</strong>, three nasal vowels, and the French <strong>r</strong> in familiar words.</p><div className="lesson-inline-actions"><Button onClick={() => void move(0)}>Practise again</Button><Link to="/learn/a1/unit/first-contact/lesson/courtesy">Next: Courtesy →</Link></div></section>}

    {step < 7 && <nav className="lesson-navigation" aria-label="Lesson navigation">{step > 0 ? <Button variant="secondary" onClick={() => void move(step - 1)}>← Previous</Button> : <span />}{step < 6 && <Button disabled={step >= furthestStep && !requirements[step]} onClick={() => void move(step + 1)}>Continue to {steps[step + 1]} →</Button>}</nav>}
  </article>;
}
