import { useEffect, useRef, useState } from "react";
import { AudioTextSelectRenderer, DictationRenderer, GuidedSpeakingRenderer, MeaningSelectRenderer, SentenceBuildRenderer, TypedRecallRenderer } from "../activities/registry";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.courtesy";
const steps = ["Warm-up", "Meet", "Meaning", "Listen", "Build", "Use", "Check", "Complete"];
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;

function Choice({ id, prompt, options, answer, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; onComplete: Complete }) {
  return <MeaningSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} prompt={prompt} options={options} answer={answer} feedback={{ [answer]: `${answer} fits this situation.` }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} />;
}

function Listening({ id, audio, options, answer, onComplete, assessment = false }: { id: string; audio: string; options: readonly string[]; answer: string; onComplete: Complete; assessment?: boolean }) {
  return <div className="listening-activity"><strong>Listen, then choose the expression.</strong><AudioTextSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} audio={audio} options={options} answer={answer} assessment={assessment} feedback={{ [answer]: `You heard ${answer}` }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} /></div>;
}

export default function CourtesyLesson() {
  const learner = useGuestLearner(lessonId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [step, setStep] = useState(0); const [furthestStep, setFurthestStep] = useState(0); const [completed, setCompleted] = useState<Set<string>>(new Set()); const [transcript, setTranscript] = useState(false); const [exit, setExit] = useState<Record<string, boolean>>({}); const [round, setRound] = useState(1); const [saveError, setSaveError] = useState<string>();
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current = true; const saved = Math.min(learner.progress?.currentStep ?? 0, 7); setStep(saved); setFurthestStep(Math.min(learner.progress?.furthestStep ?? saved, 7)); } }, [learner.loading, learner.progress]);
  useEffect(() => { headingRef.current?.focus(); }, [step]);
  useEffect(() => () => { if (sessionId.current) void learner.repository.endSession(sessionId.current); }, [learner.repository]);
  const complete: Complete = async (itemId, response, correct) => { if (correct) setCompleted(current => new Set(current).add(itemId)); if (!learner.enrollment) return; try { if (!sessionId.current) sessionId.current = (await learner.repository.startSession(lessonId, "deep_link")).id; await learner.repository.submitAttempt({ learnerId: learner.enrollment.learnerId, enrollmentId: learner.enrollment.id, sessionId: sessionId.current, lessonId, activityId: itemId.replace("item", "activity").replace(/\.\w+$/, ""), itemId, response, correct, idempotencyKey: crypto.randomUUID() }); await learner.refresh(); setSaveError(undefined); } catch { setSaveError("Progress could not be saved. You can continue this session."); } };
  const exitComplete: Complete = async (id, response, correct) => { setExit(current => ({ ...current, [id]: correct })); await complete(id, response, correct); };
  const move = async (next: number) => { setStep(next); setFurthestStep(current => Math.max(current, next)); if (learner.enrollment) { try { await learner.repository.saveLessonPosition(lessonId, next); await learner.refresh(); } catch { setSaveError("Your lesson position could not be saved."); } } };
  const has = (...ids: string[]) => ids.every(id => completed.has(id));
  const requirements = [has("item.a1.u01.l04.warmup.merci", "item.a1.u01.l04.warmup.revoir"), has("item.a1.u01.l04.notice"), has("item.a1.u01.l04.meaning.1", "item.a1.u01.l04.meaning.2", "item.a1.u01.l04.meaning.3", "item.a1.u01.l04.meaning.4", "item.a1.u01.l04.meaning.5", "item.a1.u01.l04.meaning.6"), has("item.a1.u01.l04.listen.1", "item.a1.u01.l04.listen.2", "item.a1.u01.l04.dictation.merci", "item.a1.u01.l04.dictation.please"), has("item.a1.u01.l04.build.excuse", "item.a1.u01.l04.build.thanks", "item.a1.u01.l04.build.please"), has("item.a1.u01.l04.role.greet", "item.a1.u01.l04.role.request", "item.a1.u01.l04.role.thanks"), false, false];
  const check = async () => { const values = Object.values(exit); if (values.length === 4 && values.filter(Boolean).length >= 3 && exit["item.a1.u01.l04.exit.sequence"]) { if (learner.enrollment) await learner.repository.completeLesson(lessonId); await move(7); } };
  if (learner.loading) return <p role="status">Loading Lesson 4…</p>;
  return <article className="lesson-flow lesson-player courtesy-lesson">
    <header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Lesson 4 · {steps[step]}</p><h1>Courtesy</h1><p className="page-sub">I can choose and use basic polite expressions appropriately.</p><Progress label="Lesson progress" value={step} max={7} /><ol className="lesson-stepper" aria-label="Lesson steps">{steps.map((label, index) => <li key={label} className={index === step ? "is-current" : index < step ? "is-done" : ""}><span>{index + 1}</span>{label}</li>)}</ol>{saveError && <Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>

    {step === 0 && <section className="lesson-stage lesson-two-warmup"><div className="lesson-stage-intro"><p className="learn-preview-kicker">1 · Quick retrieval</p><h2 ref={headingRef} tabIndex={-1}>Bring back two familiar expressions</h2><p>You already met these phrases. Retrieve their purpose before adding a fuller courtesy toolkit.</p></div><div className="contrast-grid"><Choice id="item.a1.u01.l04.warmup.merci" prompt="Someone helps you. What do you say?" options={["Merci.", "Bonjour."]} answer="Merci." onComplete={complete} /><Choice id="item.a1.u01.l04.warmup.revoir" prompt="You are leaving. What do you say?" options={["Au revoir.", "S’il vous plaît."]} answer="Au revoir." onComplete={complete} /></div></section>}

    {step === 1 && <section className="lesson-stage lesson-scene lesson-two-scene"><img src="/images/course/a1/unit-01/courtesy-handout-v2.png" alt="Ana politely receives a class handout from Sam near the classroom doorway." /><div className="lesson-scene__copy"><div className="lesson-stage-intro"><p className="learn-preview-kicker">2 · Meet Ana and Sam</p><h2 ref={headingRef} tabIndex={-1}>A handout at the classroom door</h2><p>Ana arrives after class has started. Listen for how she gets Sam’s attention, requests the handout, and responds when he gives it to her.</p></div><AudioControl label="Play Ana and Sam's dialogue" onPlay={() => speak("Bonjour. Excusez-moi. Le document, s'il vous plaît. Voilà. Merci beaucoup. De rien.")} onPlaySlow={() => speak("Bonjour. Excusez-moi. Le document, s'il vous plaît. Voilà. Merci beaucoup. De rien.", { rate: 0.75 })} /><Choice id="item.a1.u01.l04.notice" prompt="What happens in the exchange?" options={["Ana politely asks for and receives a handout", "Ana spells her name", "Ana says goodbye"]} answer="Ana politely asks for and receives a handout" onComplete={complete} /><Button variant="secondary" onClick={() => setTranscript(value => !value)}>{transcript ? "Hide transcript" : "Show transcript"}</Button>{transcript && <div className="dialogue">{[["Ana", "Bonjour. Excusez-moi.", "Hello. Excuse me."], ["Sam", "Bonjour.", "Hello."], ["Ana", "Le document, s’il vous plaît.", "The handout, please."], ["Sam", "Voilà.", "Here you are."], ["Ana", "Merci beaucoup.", "Thank you very much."], ["Sam", "De rien.", "You're welcome."]].map(([speaker, french, english]) => <div key={french}><strong>{speaker}</strong><span><b lang="fr">{french}</b><small>{english}</small></span><AudioControl label={`Play ${speaker}'s line`} onPlay={() => speak(french)} onPlaySlow={() => speak(french, { rate: 0.75 })} /></div>)}</div>}</div></section>}

    {step === 2 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">3 · Meaning and use</p><h2 ref={headingRef} tabIndex={-1}>Choose the phrase that fits</h2><p>Courtesy depends on the situation—not just translation.</p></div><div className="summary-grid"><Card title="Thanks"><p><strong>Merci</strong> is everyday “thank you.” Add <strong>beaucoup</strong> when you are especially grateful. Reply with <strong>de rien</strong>.</p></Card><Card title="Requests and interruptions"><p><strong>S’il vous plaît</strong> marks a polite request. <strong>Excusez-moi</strong> gets attention; <strong>pardon</strong> is useful for a brief accidental apology.</p></Card></div><div className="activity-stack"><Choice id="item.a1.u01.l04.meaning.1" prompt="Someone gives you a document." options={["Merci.", "S’il vous plaît.", "Pardon."]} answer="Merci." onComplete={complete} /><Choice id="item.a1.u01.l04.meaning.2" prompt="You politely ask for a coffee." options={["S’il vous plaît.", "De rien.", "Pardon."]} answer="S’il vous plaît." onComplete={complete} /><Choice id="item.a1.u01.l04.meaning.3" prompt="You need to interrupt a teacher politely." options={["Excusez-moi.", "Merci beaucoup.", "De rien."]} answer="Excusez-moi." onComplete={complete} /><Choice id="item.a1.u01.l04.meaning.4" prompt="You accidentally step on someone’s foot." options={["Pardon.", "S’il vous plaît.", "Bonjour."]} answer="Pardon." onComplete={complete} /><Choice id="item.a1.u01.l04.meaning.5" prompt="Someone says “Merci.”" options={["De rien.", "Excusez-moi.", "Au revoir."]} answer="De rien." onComplete={complete} /><Choice id="item.a1.u01.l04.meaning.6" prompt="You are especially grateful." options={["Merci beaucoup.", "Pardon.", "De rien."]} answer="Merci beaucoup." onComplete={complete} /></div><Feedback title="A safe beginner choice" tone="info">You will study <em>tu</em> and <em>vous</em> fully later. For now, expressions with <em>vous</em> are safe polite choices with an unfamiliar adult or teacher.</Feedback></section>}

    {step === 3 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">4 · Listen and write</p><h2 ref={headingRef} tabIndex={-1}>Recognize the phrase, then retrieve it</h2></div><div className="activity-stack"><Listening id="item.a1.u01.l04.listen.1" audio="pardon" options={["merci", "de rien", "pardon"]} answer="pardon" onComplete={complete} /><Listening id="item.a1.u01.l04.listen.2" audio="merci beaucoup" options={["merci beaucoup", "bonjour", "bonne journée"]} answer="merci beaucoup" onComplete={complete} /><DictationRenderer activityId="activity.a1.u01.l04.dictation" itemId="item.a1.u01.l04.dictation.merci" audio="Merci." answers={["Merci."]} policy={{ accents: "required", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /><DictationRenderer activityId="activity.a1.u01.l04.dictation" itemId="item.a1.u01.l04.dictation.please" audio="S'il vous plaît." answers={["S'il vous plaît.", "S’il vous plaît."]} policy={{ accents: "forgiving", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /></div></section>}

    {step === 4 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">5 · Build the expressions</p><h2 ref={headingRef} tabIndex={-1}>Keep each useful chunk together</h2><p>The apostrophe stays inside <strong>S’il</strong>; it is one contracted word.</p></div><div className="activity-stack"><SentenceBuildRenderer activityId="activity.a1.u01.l04.build" itemId="item.a1.u01.l04.build.excuse" prompt="Build ‘Excuse me.’" tokens={["Excusez-moi", "."]} answer="Excusez-moi ." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /><SentenceBuildRenderer activityId="activity.a1.u01.l04.build" itemId="item.a1.u01.l04.build.thanks" prompt="Build ‘Thank you very much.’" tokens={["beaucoup", ".", "Merci"]} answer="Merci beaucoup ." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /><SentenceBuildRenderer activityId="activity.a1.u01.l04.build" itemId="item.a1.u01.l04.build.please" prompt="Build ‘Please.’" tokens={["plaît", ".", "S’il", "vous"]} answer="S’il vous plaît ." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /></div></section>}

    {step === 5 && <section className="lesson-stage"><div className="lesson-stage-intro"><p className="learn-preview-kicker">6 · Use it</p><h2 ref={headingRef} tabIndex={-1}>Help Ana complete the exchange</h2><p>Choose the function at each moment. Speaking afterward is optional.</p></div><div className="activity-stack"><Choice id="item.a1.u01.l04.role.greet" prompt="Ana enters and acknowledges Sam." options={["Bonjour.", "Pardon.", "De rien."]} answer="Bonjour." onComplete={complete} /><Choice id="item.a1.u01.l04.role.request" prompt="Ana points to the handout she needs." options={["Le document, s’il vous plaît.", "Le document, de rien.", "Merci le document."]} answer="Le document, s’il vous plaît." onComplete={complete} /><Choice id="item.a1.u01.l04.role.thanks" prompt="Sam gives Ana the handout." options={["Merci beaucoup.", "Excusez-moi.", "S’il vous plaît."]} answer="Merci beaucoup." onComplete={complete} /></div><aside className="role-play"><strong>Optional speaking</strong><p>Play Ana. Say the complete exchange as three short groups.</p><GuidedSpeakingRenderer activityId="activity.a1.u01.l04.speaking" itemId="item.a1.u01.l04.speaking" prompt="Bonjour. Excusez-moi. Le document, s’il vous plaît. Merci beaucoup." model="Bonjour. Excusez-moi. Le document, s'il vous plaît. Merci beaucoup." onSubmit={({ envelope, evaluation }) => complete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /></aside></section>}

    {step === 6 && <section className="lesson-stage lesson-check" key={round}><p className="learn-preview-kicker">7 · Check</p><h2 ref={headingRef} tabIndex={-1}>Can you be polite without hints?</h2><p>Pass 3 of 4, including the complete exchange.</p><Choice id="item.a1.u01.l04.exit.apology" prompt="You accidentally bump into someone." options={["Pardon.", "De rien.", "Merci beaucoup."]} answer="Pardon." onComplete={exitComplete} /><div className="listening-activity"><strong>Sam says “Merci.” What is the natural response?</strong><AudioControl label="Play Merci" onPlay={() => speak("Merci.")} onPlaySlow={() => speak("Merci.", { rate: 0.75 })} /><Choice id="item.a1.u01.l04.exit.response" prompt="Choose your response." options={["De rien.", "S’il vous plaît.", "Excusez-moi."]} answer="De rien." onComplete={exitComplete} /></div><TypedRecallRenderer activityId="activity.a1.u01.l04.exit" itemId="item.a1.u01.l04.exit.excuse" prompt="Type ‘Excuse me’ for a polite interruption." answers={["Excusez-moi."]} policy={{ accents: "forgiving", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => exitComplete(envelope.itemId, String(envelope.response), evaluation.outcome === "correct")} /><Choice id="item.a1.u01.l04.exit.sequence" prompt="Choose the complete polite classroom exchange." options={["Bonjour. Le document, s’il vous plaît. Merci.", "Pardon. Le document. De rien.", "Au revoir. Merci. Bonjour."]} answer="Bonjour. Le document, s’il vous plaît. Merci." onComplete={exitComplete} />{Object.keys(exit).length === 4 && <Button onClick={() => void check()}>Check my lesson result</Button>}{Object.keys(exit).length === 4 && !(Object.values(exit).filter(Boolean).length >= 3 && exit["item.a1.u01.l04.exit.sequence"]) && <div className="remediation"><Feedback title="Review and retry" tone="error">Use <strong>s’il vous plaît</strong> with a request, <strong>merci</strong> after receiving something, and <strong>pardon</strong> for a brief accident.</Feedback><Button onClick={() => { setRound(value => value + 1); setExit({}); }}>Retry lesson check</Button></div>}</section>}

    {step === 7 && <section className="lesson-stage lesson-summary"><p className="lesson-celebration" aria-hidden="true">✓</p><p className="learn-preview-kicker">Lesson complete</p><h2 ref={headingRef} tabIndex={-1}>You can handle a polite everyday exchange</h2><p>You can get someone’s attention, mark a request, apologize briefly, give thanks, and respond to thanks.</p><div className="lesson-inline-actions"><Button onClick={() => void move(0)}>Practise again</Button><Link to="/learn/a1/unit/first-contact">Next: Classroom survival →</Link></div></section>}
    {step < 7 && <nav className="lesson-navigation" aria-label="Lesson navigation">{step > 0 ? <Button variant="secondary" onClick={() => void move(step - 1)}>← Previous</Button> : <span />}{step < 6 && <Button disabled={step >= furthestStep && !requirements[step]} onClick={() => void move(step + 1)}>Continue to {steps[step + 1]} →</Button>}</nav>}
  </article>;
}
