import { useEffect, useRef, useState } from "react";
import { GuidedSpeakingRenderer, MeaningSelectRenderer, SentenceBuildRenderer, TypedRecallRenderer } from "../activities/registry";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.review";
const steps = ["Start", "Greetings", "Names & sounds", "Courtesy", "Repair", "Scenario", "Results"];
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;
function Choice({ id, prompt, options, answer, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; onComplete: Complete }) { return <MeaningSelectRenderer activityId={id.replace("item","activity").replace(/\.\w+$/,"")} itemId={id} prompt={prompt} options={options} answer={answer} onSubmit={({envelope,evaluation}) => onComplete(id,String(envelope.response),evaluation.outcome === "correct")}/>; }

export default function IntegratedReviewLesson() {
  const learner = useGuestLearner(lessonId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [step,setStep] = useState(0); const [furthest,setFurthest] = useState(0); const [done,setDone] = useState<Set<string>>(new Set()); const [saveError,setSaveError] = useState<string>();
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current=true; const saved=Math.min(learner.progress?.currentStep??0,6); setStep(saved); setFurthest(Math.min(learner.progress?.furthestStep??saved,6)); } },[learner.loading,learner.progress]);
  useEffect(() => { headingRef.current?.focus(); },[step]); useEffect(() => () => { if(sessionId.current) void learner.repository.endSession(sessionId.current); },[learner.repository]);
  const complete: Complete = async (id,response,correct) => { if(correct) setDone(current=>new Set(current).add(id)); if(!learner.enrollment)return; try { if(!sessionId.current)sessionId.current=(await learner.repository.startSession(lessonId,"deep_link")).id; await learner.repository.submitAttempt({learnerId:learner.enrollment.learnerId,enrollmentId:learner.enrollment.id,sessionId:sessionId.current,lessonId,activityId:id.replace("item","activity").replace(/\.\w+$/,"") ,itemId:id,response,correct,idempotencyKey:crypto.randomUUID()}); await learner.refresh();setSaveError(undefined);}catch{setSaveError("Progress could not be saved. You can continue this review.");} };
  const move=async(next:number)=>{setStep(next);setFurthest(current=>Math.max(current,next));if(learner.enrollment){try{await learner.repository.saveLessonPosition(lessonId,next);await learner.refresh();}catch{setSaveError("Your review position could not be saved.");}}};
  const has=(...ids:string[])=>ids.every(id=>done.has(id));
  const requirements=[has("item.a1.u01.r01.start"),has("item.a1.u01.r01.greet.1","item.a1.u01.r01.greet.2","item.a1.u01.r01.greet.3"),has("item.a1.u01.r01.name","item.a1.u01.r01.spell","item.a1.u01.r01.sound.1","item.a1.u01.r01.sound.2"),has("item.a1.u01.r01.courtesy.1","item.a1.u01.r01.courtesy.2","item.a1.u01.r01.courtesy.3"),has("item.a1.u01.r01.repair.1","item.a1.u01.r01.repair.2","item.a1.u01.r01.repair.3"),has("item.a1.u01.r01.scenario.1","item.a1.u01.r01.scenario.2","item.a1.u01.r01.scenario.3","item.a1.u01.r01.scenario.4","item.a1.u01.r01.scenario.5","item.a1.u01.r01.scenario.6"),false];
  const finish=async()=>{if(learner.enrollment)await learner.repository.completeLesson(lessonId);await move(6);};
  if(learner.loading)return <p role="status">Loading Unit 1 review…</p>;
  return <article className="lesson-flow lesson-player integrated-review-lesson"><header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Integrated review · {steps[step]}</p><h1>First contact review</h1><p className="page-sub">Retrieve greetings, spelling, sounds, courtesy, and communication repair in connected situations.</p><Progress label="Review progress" value={step} max={6}/><ol className="lesson-stepper" aria-label="Review steps">{steps.map((label,index)=><li key={label} className={index===step?"is-current":index<step?"is-done":""}><span>{index+1}</span>{label}</li>)}</ol>{saveError&&<Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>
  {step===0&&<section className="lesson-stage lesson-scene lesson-two-scene"><img src="/images/course/a1/unit-01/integrated-review-evening-v1.png" alt="Léa asks Lucas to spell his name at an evening French-class check-in table."/><div className="lesson-scene__copy"><div className="lesson-stage-intro"><p className="learn-preview-kicker">Meet Léa and Lucas</p><h2 ref={headingRef} tabIndex={-1}>An evening class, from arrival to goodbye</h2><p>This review gives immediate correction and does not erase completed lessons. Work through the full interaction, then see which skills are ready and which need another listen.</p></div><AudioControl label="Play the opening exchange" onPlay={()=>speak("Bonsoir. Votre prénom ? Lucas. Comment ça s'écrit ? L, U, C, A, S. Merci.")} onPlaySlow={()=>speak("Bonsoir. Votre prénom ? Lucas. Comment ça s'écrit ? L, U, C, A, S. Merci.",{rate:.75})}/><Choice id="item.a1.u01.r01.start" prompt="What time of day is this class?" options={["Evening","Morning","Midday"]} answer="Evening" onComplete={complete}/></div></section>}
  {step===1&&<section className="lesson-stage"><p className="learn-preview-kicker">Greetings</p><h2 ref={headingRef} tabIndex={-1}>Arrive and leave at the right time</h2><div className="activity-stack"><Choice id="item.a1.u01.r01.greet.1" prompt="Léa arrives at 6:30 p.m." options={["Bonsoir !","Bonjour !","Bonne soirée !"]} answer="Bonsoir !" onComplete={complete}/><Choice id="item.a1.u01.r01.greet.2" prompt="Lucas leaves and will return tomorrow." options={["À demain !","Bonjour !","Pardon !"]} answer="À demain !" onComplete={complete}/><Choice id="item.a1.u01.r01.greet.3" prompt="Léa leaves and wishes Lucas a pleasant evening." options={["Bonne soirée !","Bonsoir !","Bonne journée !"]} answer="Bonne soirée !" onComplete={complete}/></div></section>}
  {step===2&&<section className="lesson-stage"><p className="learn-preview-kicker">Names and sounds</p><h2 ref={headingRef} tabIndex={-1}>Listen across spelling and sound contrasts</h2><div className="activity-stack"><div className="listening-activity"><AudioControl label="Hear Léa spelled" onPlay={()=>speak("L, É, A")}/><TypedRecallRenderer activityId="activity.a1.u01.r01.name" itemId="item.a1.u01.r01.name" prompt="Type the name you hear." answers={["Léa"]} policy={{accents:"required",punctuation:"optional"}} onSubmit={({envelope,evaluation})=>complete(envelope.itemId,String(envelope.response),evaluation.outcome==="correct")}/></div><Choice id="item.a1.u01.r01.spell" prompt="Politely ask Lucas to spell his name." options={["Pouvez-vous épeler, s’il vous plaît ?","Comment dit-on Lucas ?","Plus lentement."]} answer="Pouvez-vous épeler, s’il vous plaît ?" onComplete={complete}/><div className="listening-activity"><AudioControl label="Hear rue" onPlay={()=>speak("rue")}/><Choice id="item.a1.u01.r01.sound.1" prompt="Which word do you hear?" options={["rue","roue"]} answer="rue" onComplete={complete}/></div><div className="listening-activity"><AudioControl label="Hear son" onPlay={()=>speak("son")}/><Choice id="item.a1.u01.r01.sound.2" prompt="Which nasal word do you hear?" options={["sans","son","sain"]} answer="son" onComplete={complete}/></div></div></section>}
  {step===3&&<section className="lesson-stage"><p className="learn-preview-kicker">Courtesy</p><h2 ref={headingRef} tabIndex={-1}>Choose courtesy by purpose</h2><div className="activity-stack"><Choice id="item.a1.u01.r01.courtesy.1" prompt="Lucas gives Léa a handout." options={["Merci.","S’il vous plaît.","Pardon."]} answer="Merci." onComplete={complete}/><Choice id="item.a1.u01.r01.courtesy.2" prompt="Léa needs to interrupt the facilitator." options={["Excusez-moi.","De rien.","Au revoir."]} answer="Excusez-moi." onComplete={complete}/><Choice id="item.a1.u01.r01.courtesy.3" prompt="Lucas says ‘Merci’." options={["De rien.","Pardon.","Bonsoir."]} answer="De rien." onComplete={complete}/></div></section>}
  {step===4&&<section className="lesson-stage"><p className="learn-preview-kicker">Communication repair</p><h2 ref={headingRef} tabIndex={-1}>Ask for the specific help you need</h2><div className="activity-stack"><Choice id="item.a1.u01.r01.repair.1" prompt="The instruction was too fast." options={["Plus lentement, s’il vous plaît.","Je comprends.","De rien."]} answer="Plus lentement, s’il vous plaît." onComplete={complete}/><TypedRecallRenderer activityId="activity.a1.u01.r01.repair" itemId="item.a1.u01.r01.repair.2" prompt="Type ‘I don’t understand.’ in French." answers={["Je ne comprends pas."]} policy={{accents:"forgiving",punctuation:"optional"}} onSubmit={({envelope,evaluation})=>complete(envelope.itemId,String(envelope.response),evaluation.outcome==="correct")}/><SentenceBuildRenderer activityId="activity.a1.u01.r01.repair" itemId="item.a1.u01.r01.repair.3" prompt="Build the polite repetition request." tokens={["répéter","s’il vous plaît","Pouvez-vous","?",","]} answer="Pouvez-vous répéter , s’il vous plaît ?" onSubmit={({envelope,evaluation})=>complete(envelope.itemId,String(envelope.response),evaluation.outcome==="correct")}/></div></section>}
  {step===5&&<section className="lesson-stage"><p className="learn-preview-kicker">Integrated scenario</p><h2 ref={headingRef} tabIndex={-1}>Take Léa through the whole evening class</h2><p>Complete each function. Speaking is available but optional.</p><div className="activity-stack"><Choice id="item.a1.u01.r01.scenario.1" prompt="Arrive in the evening." options={["Bonsoir !","Bonne soirée !"]} answer="Bonsoir !" onComplete={complete}/><Choice id="item.a1.u01.r01.scenario.2" prompt="Ask for a document politely." options={["Le document, s’il vous plaît.","Merci le document."]} answer="Le document, s’il vous plaît." onComplete={complete}/><Choice id="item.a1.u01.r01.scenario.3" prompt="Respond after receiving it." options={["Merci.","De rien."]} answer="Merci." onComplete={complete}/><Choice id="item.a1.u01.r01.scenario.4" prompt="Ask to hear the instruction again." options={["Pouvez-vous répéter, s’il vous plaît ?","Je comprends."]} answer="Pouvez-vous répéter, s’il vous plaît ?" onComplete={complete}/><Choice id="item.a1.u01.r01.scenario.5" prompt="Confirm that you understand now." options={["Je comprends.","Je ne comprends pas."]} answer="Je comprends." onComplete={complete}/><Choice id="item.a1.u01.r01.scenario.6" prompt="Leave with an evening wish." options={["Bonne soirée !","Bonsoir !"]} answer="Bonne soirée !" onComplete={complete}/></div><aside className="role-play"><strong>Optional speaking transfer</strong><GuidedSpeakingRenderer activityId="activity.a1.u01.r01.speaking" itemId="item.a1.u01.r01.speaking" prompt="Greet, ask for repetition, thank the speaker, and leave." model="Bonsoir. Pouvez-vous répéter, s'il vous plaît ? Merci. Bonne soirée." onSubmit={({envelope,evaluation})=>complete(envelope.itemId,String(envelope.response),evaluation.outcome==="correct")}/></aside>{requirements[5]&&<Button onClick={()=>void finish()}>Finish review and see results</Button>}</section>}
  {step===6&&<section className="lesson-stage lesson-summary"><p className="lesson-celebration">✓</p><p className="learn-preview-kicker">Review complete</p><h2 ref={headingRef} tabIndex={-1}>Your Unit 1 skills worked together</h2><div className="summary-grid"><Card title="Context ready"><p>Arrival and leaving greetings; courtesy choices.</p></Card><Card title="Listening ready"><p>Name spelling and core sound contrasts.</p></Card><Card title="Communication strategy ready"><p>Repetition, slower speech, and understanding.</p></Card><Card title="Keep reviewing"><p>Future reviews will rotate speakers and examples so recall—not recording memory—gets stronger.</p></Card></div><div className="lesson-inline-actions"><Button onClick={()=>void move(0)}>Review again</Button><Link to="/learn/a1/unit/first-contact">Next: Capability assessment →</Link></div></section>}
  {step<5&&<nav className="lesson-navigation" aria-label="Review navigation">{step>0?<Button variant="secondary" onClick={()=>void move(step-1)}>← Previous</Button>:<span/>}<Button disabled={step>=furthest&&!requirements[step]} onClick={()=>void move(step+1)}>Continue to {steps[step+1]} →</Button></nav>}
  </article>;
}
