import { useEffect, useRef, useState } from "react";
import { AudioTextSelectRenderer, MeaningSelectRenderer, SentenceBuildRenderer, TypedRecallRenderer } from "../activities/registry";
import type { MediaContent } from "../domain/content";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { contentRepository } from "../repositories/content";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.greetings";
const firstItemId = "item.a1.u01.l01.meaning.001";
const steps = ["Meet", "Notice", "Choose", "Listen", "Build", "Speak", "Check", "Complete"];
const dialogue = {
  arriving: [["Sofia", "Bonjour !", "Hello!"], ["Ira", "Bonjour !", "Hello!"], ["Sofia", "Ça va ?", "How are you?"], ["Ira", "Ça va bien, merci.", "I’m well, thank you."]],
  leaving: [["Sofia", "Au revoir !", "Goodbye!"], ["Ira", "À demain ! Bonne journée !", "See you tomorrow! Have a good day!"]],
} as const;
const phrases = [
  ["Bonjour !", "Hello / Good morning", "bon | jour"], ["Bonsoir !", "Good evening", "bon | soir"], ["Salut !", "Hi / Bye", "sa | lut"], ["Au revoir !", "Goodbye", "au | re | voir"],
  ["À bientôt !", "See you soon", "à | bien | tôt"], ["À demain !", "See you tomorrow", "à | de | main"], ["Bonne journée !", "Have a good day", "bonne | jour | née"], ["Bonne soirée !", "Have a good evening", "bonne | soi | rée"],
] as const;
const practice = [
  { id: firstItemId, prompt: "It is 9:00 a.m. You greet your teacher.", options: ["Bonjour !", "Bonsoir !", "Au revoir !"], answer: "Bonjour !", feedback: { "Bonjour !": "Bonjour is the polite daytime greeting.", "Bonsoir !": "Bonsoir is an evening greeting.", "Au revoir !": "Au revoir is used when leaving." } },
  { id: "item.a1.u01.l01.meaning.002", prompt: "You leave a store.", options: ["Au revoir !", "Bonjour !", "Salut !"], answer: "Au revoir !", feedback: { "Au revoir !": "Au revoir is a safe general goodbye.", "Bonjour !": "Bonjour greets someone as you arrive.", "Salut !": "Salut is informal." } },
  { id: "item.a1.u01.l01.meaning.003", prompt: "You greet a close friend informally.", options: ["Salut !", "Bonne journée !", "Au revoir !"], answer: "Salut !", feedback: { "Salut !": "Salut fits a close friend.", "Bonne journée !": "Bonne journée is a leaving wish.", "Au revoir !": "Au revoir is a goodbye." } },
  { id: "item.a1.u01.l01.meaning.004", prompt: "It is evening and you enter a restaurant.", options: ["Bonsoir !", "Bonne soirée !", "À demain !"], answer: "Bonsoir !", feedback: { "Bonsoir !": "Bonsoir greets someone in the evening.", "Bonne soirée !": "Bonne soirée is normally said when leaving.", "À demain !": "À demain means see you tomorrow." } },
] as const;
const listening = [
  ["001", "Bonjour !", ["Bonjour !", "Bonne journée !", "Bonsoir !"]], ["002", "À demain !", ["Au revoir !", "À demain !", "À bientôt !"]],
  ["003", "Bonne soirée !", ["Bonsoir !", "Bonne soirée !", "Bonjour !"]], ["004", "Salut !", ["Salut !", "S'il vous plaît !", "Merci !"]],
] as const;
const listeningGuidance: Record<string, string> = {
  "Bonjour !": "Bonjour means ‘Hello’ or ‘Good morning.’ Use it to greet someone during the day.",
  "À demain !": "À demain means ‘See you tomorrow.’ Use it when leaving someone you expect to see the next day.",
  "Bonne soirée !": "Bonne soirée means ‘Have a good evening.’ It is a friendly wish used when leaving in the evening.",
  "Salut !": "Salut means ‘Hi’ or ‘Bye.’ Use it informally with friends and people you know well.",
  "Bonsoir !": "Bonsoir means ‘Good evening.’ Use it to greet someone in the evening.",
};
const builders = [
  ["001", "Build ‘Have a good day!’", ["journée", "!", "Bonne"], "Bonne journée !"],
  ["002", "Build ‘See you tomorrow!’", ["demain", "!", "À"], "À demain !"],
  ["003", "Build a daytime greeting.", ["!", "Bonjour"], "Bonjour !"],
] as const;
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;

function Choice({ id, prompt, options, answer, feedback, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; feedback?: Record<string, string>; onComplete: Complete }) {
  return <MeaningSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} prompt={prompt} options={options} answer={answer} feedback={feedback} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} />;
}
function Listening({ id, audio, options, onComplete, assessment = false }: { id: string; audio: string; options: readonly string[]; onComplete: Complete; assessment?: boolean }) {
  return <div className="listening-activity"><strong>Which expression do you hear?</strong><AudioTextSelectRenderer activityId="activity.a1.u01.l01.listening" itemId={id} audio={audio} options={options} answer={audio} assessment={assessment} feedback={{ [audio]: listeningGuidance[audio] }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} /></div>;
}
function Builder({ item, onComplete }: { item: typeof builders[number]; onComplete: Complete }) {
  return <SentenceBuildRenderer activityId="activity.a1.u01.l01.builder" itemId={`item.a1.u01.l01.builder.${item[0]}`} prompt={item[1]} tokens={item[2]} answer={item[3]} onSubmit={({ envelope, evaluation }) => onComplete(`item.a1.u01.l01.builder.${item[0]}`, Array.isArray(envelope.response) ? envelope.response.join(" ") : String(envelope.response), evaluation.outcome === "correct")} />;
}
function Speaking({ id, prompt, model, onComplete }: { id: string; prompt: string; model: string; onComplete: Complete }) {
  const recorder = useRef<MediaRecorder | undefined>(undefined); const chunks = useRef<Blob[]>([]); const [recording, setRecording] = useState(false); const [url, setUrl] = useState<string>(); const [unavailable, setUnavailable] = useState(false); const [checks, setChecks] = useState([false, false, false]); const [submitted, setSubmitted] = useState(false);
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const next = new MediaRecorder(stream); recorder.current = next; chunks.current = []; next.ondataavailable = event => chunks.current.push(event.data); next.onstop = () => { setUrl(URL.createObjectURL(new Blob(chunks.current, { type: next.mimeType }))); stream.getTracks().forEach(track => track.stop()); }; next.start(); setRecording(true); } catch { setUnavailable(true); } };
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  const labels = ["The expression fits the situation", "I can understand my words", "I spoke it as one short group"];
  return <div className="speaking-practice"><h3>{prompt}</h3><p>Your recording stays on this page and is never saved.</p><div className="lesson-inline-actions"><AudioControl label="Hear the model" onPlay={() => speak(model)} onPlaySlow={() => speak(model, { rate: 0.75 })} />{!recording ? <Button onClick={() => void start()}>Record my answer</Button> : <Button onClick={() => { recorder.current?.stop(); setRecording(false); }}>Stop recording</Button>}</div>{unavailable && <Feedback title="Microphone unavailable" tone="info">Say it aloud and compare with the model.</Feedback>}{url && <audio controls src={url} aria-label="Play your recording" />}{(url || unavailable) && !submitted && <fieldset className="speaking-checklist"><legend>Review your speaking</legend>{labels.map((label, index) => <label key={label}><input type="checkbox" checked={checks[index]} onChange={() => setChecks(current => current.map((value, i) => i === index ? !value : value))} /> {label}</label>)}<Button disabled={!checks.some(Boolean)} onClick={() => { setSubmitted(true); void onComplete(id, "self-reviewed", checks.filter(Boolean).length >= 2); }}>Submit self-review</Button></fieldset>}{submitted && <Feedback title="Speaking saved" tone="success">Model: {model}</Feedback>}</div>;
}

export default function LessonFlowPreview() {
  const learner = useGuestLearner(lessonId, firstItemId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [media, setMedia] = useState<MediaContent>(); const [step, setStep] = useState(0); const [phase, setPhase] = useState<keyof typeof dialogue>("arriving"); const [transcript, setTranscript] = useState<"none" | "fr" | "en">("none"); const [sceneAnswer, setSceneAnswer] = useState<string>(); const [role, setRole] = useState<"Sofia" | "Ira">(); const [completed, setCompleted] = useState<Set<string>>(new Set()); const [exitResults, setExitResults] = useState<Record<string, boolean>>({}); const [exitRound, setExitRound] = useState(1); const [exitStatus, setExitStatus] = useState<"idle" | "passed" | "failed">("idle"); const [saveError, setSaveError] = useState<string>();
  const [furthestStep, setFurthestStep] = useState(0);
  useEffect(() => { void contentRepository.resolveMedia("media.image.a1.u01.l01.arrival.v3").then(setMedia); }, []);
  // IndexedDB hydration establishes the safe resume boundary after mount.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current = true; setStep(Math.min(learner.progress?.currentStep ?? 0, 7)); setFurthestStep(Math.min(learner.progress?.furthestStep ?? learner.progress?.currentStep ?? 0, 7)); if (learner.progress?.status === "completed") setExitStatus("passed"); } }, [learner.loading, learner.progress]);
  useEffect(() => { headingRef.current?.focus(); }, [step]);
  useEffect(() => () => { if (sessionId.current) void learner.repository.endSession(sessionId.current); }, [learner.repository]);
  const complete: Complete = async (itemId, response, correct) => { if (correct) setCompleted(current => new Set(current).add(itemId)); if (!learner.enrollment) return; try { if (!sessionId.current) sessionId.current = (await learner.repository.startSession(lessonId, "deep_link")).id; await learner.repository.submitAttempt({ learnerId: learner.enrollment.learnerId, enrollmentId: learner.enrollment.id, sessionId: sessionId.current, lessonId, activityId: itemId.replace("item", "activity").replace(/\.\w+$/, ""), itemId, response, correct, idempotencyKey: crypto.randomUUID() }); setSaveError(undefined); await learner.refresh(); } catch { setSaveError("Progress could not be saved. You can continue this session."); } };
  const exitComplete: Complete = async (id, response, correct) => { setExitResults(current => ({ ...current, [id]: correct })); await complete(id, response, correct); };
  const move = async (next: number) => { setStep(next); setFurthestStep(current => Math.max(current, next)); if (learner.enrollment) { try { await learner.repository.saveLessonPosition(lessonId, next); await learner.refresh(); } catch { setSaveError("Your lesson position could not be saved."); } } };
  const checkExit = async () => { const values = Object.values(exitResults); const passed = values.filter(Boolean).length >= 3 && exitResults["item.a1.u01.l01.exit.typed"] === true; if (passed) { setExitStatus("passed"); if (learner.enrollment) await learner.repository.completeLesson(lessonId); await move(7); } else setExitStatus("failed"); };
  const stepRequirements = [completed.has(`item.a1.u01.l01.notice.${phase}`), completed.has("item.a1.u01.l01.contrast.day") && completed.has("item.a1.u01.l01.contrast.evening"), practice.every(item => completed.has(item.id)), listening.every(item => completed.has(`item.a1.u01.l01.listening.${item[0]}`)), builders.every(item => completed.has(`item.a1.u01.l01.builder.${item[0]}`)) && completed.has("item.a1.u01.l01.delayed") && completed.has("item.a1.u01.l01.transfer"), completed.has("item.a1.u01.l01.speaking.001") && completed.has("item.a1.u01.l01.speaking.002"), false, false];
  if (!media || learner.loading) return <p role="status">Loading Lesson 1…</p>;
  const lines = dialogue[phase]; const fullDialogue = lines.map(line => line[1]).join(" ");
  return <article className="lesson-flow lesson-player">
    <header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Lesson 1 · {steps[step]}</p><h1>Greetings and farewells</h1><p className="page-sub">I can choose and use an appropriate greeting or farewell.</p><Progress label="Lesson progress" value={step} max={7} /><ol className="lesson-stepper" aria-label="Lesson steps">{steps.map((label, index) => <li key={label} className={index === step ? "is-current" : index < step ? "is-done" : ""}><span>{index + 1}</span>{label}</li>)}</ol>{learner.enrollment ? <p className="lesson-save-status">{learner.progress?.status === "completed" ? "Completed · saved on this device" : `Position saved · ${learner.progress?.attemptCount ?? 0} attempts`}</p> : <p className="lesson-save-status">Preview mode · <Link to="/learn/a1">Start A1 to save progress</Link></p>}{saveError && <Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>

    {step === 0 && <section className="lesson-stage lesson-scene"><img src={media.uri} alt={media.accessibility_description ?? ""} /><div className="lesson-scene__copy"><p className="learn-preview-kicker">1 · Meet the language</p><h2 ref={headingRef} tabIndex={-1}>A morning at language school</h2><div className="lesson-tabs"><Button variant={phase === "arriving" ? "primary" : "secondary"} onClick={() => { setPhase("arriving"); setSceneAnswer(undefined); }}>Arriving</Button><Button variant={phase === "leaving" ? "primary" : "secondary"} onClick={() => { setPhase("leaving"); setSceneAnswer(undefined); }}>Leaving later</Button></div><p>Listen before opening the transcript. Are they arriving or leaving?</p><AudioControl label={`Play ${phase} dialogue`} onPlay={() => speak(fullDialogue)} onPlaySlow={() => speak(fullDialogue, { rate: 0.75 })} /><div className="lesson-options">{(["arriving", "leaving"] as const).map(answer => <Button key={answer} variant={sceneAnswer === answer ? "primary" : "secondary"} onClick={() => { setSceneAnswer(answer); void complete(`item.a1.u01.l01.notice.${phase}`, answer, answer === phase); }}>They are {answer}</Button>)}</div>{sceneAnswer && <Feedback title={sceneAnswer === phase ? "Correct" : "Listen again"} tone={sceneAnswer === phase ? "success" : "error"}>{phase === "arriving" ? "Bonjour signals a daytime meeting." : "Au revoir and à demain signal departure."}</Feedback>}<div className="lesson-inline-actions"><Button variant="secondary" onClick={() => setTranscript("fr")}>Show French</Button><Button variant="secondary" disabled={transcript === "none"} onClick={() => setTranscript("en")}>Show English support</Button></div>{transcript !== "none" && <div className="dialogue">{lines.map(([speaker, french, english]) => <div key={`${speaker}-${french}`}><strong>{speaker}</strong><span><b>{french}</b>{transcript === "en" && <small>{english}</small>}</span><AudioControl label={`Play ${speaker}'s line`} onPlay={() => speak(french)} onPlaySlow={() => speak(french, { rate: 0.75 })} /></div>)}</div>}<aside className="role-play"><strong>Optional: join the dialogue</strong><p>Choose a role, then say that character’s lines when you hear the other speaker.</p><div className="lesson-options">{(["Sofia", "Ira"] as const).map(name => <Button key={name} variant={role === name ? "primary" : "secondary"} onClick={() => setRole(name)}>Play {name}</Button>)}</div>{role && <Feedback title={`You are ${role}`} tone="info">Your cue: {lines.find(line => line[0] === role)?.[2] ?? "Listen and respond naturally."}</Feedback>}</aside></div></section>}

    {step === 1 && <section className="lesson-stage"><p className="learn-preview-kicker">2 · Notice and pronounce</p><h2 ref={headingRef} tabIndex={-1}>Arrival is different from a leaving wish</h2><div className="lesson-rule-grid"><Card title="When you arrive"><p><strong>Bonjour</strong> by day; <strong>bonsoir</strong> in the evening.</p></Card><Card title="When you leave"><p><strong>Bonne journée</strong> by day; <strong>bonne soirée</strong> in the evening.</p></Card></div><div className="contrast-grid"><Choice id="item.a1.u01.l01.contrast.day" prompt="Daytime: you are entering. What do you say?" options={["Bonjour !", "Bonne journée !"]} answer="Bonjour !" onComplete={complete} /><Choice id="item.a1.u01.l01.contrast.evening" prompt="Evening: you are leaving. What do you say?" options={["Bonsoir !", "Bonne soirée !"]} answer="Bonne soirée !" onComplete={complete} /></div><h3>Hear the phrase groups</h3><div className="phrase-guide">{phrases.map(([french, english, groups]) => <button key={french} onClick={() => speak(french, { rate: 0.75 })}><span>🔊</span><strong>{french}</strong><span>{english}</span><small>{groups}</small></button>)}</div></section>}

    {step === 2 && <section className="lesson-stage"><p className="learn-preview-kicker">3 · Choose</p><h2 ref={headingRef} tabIndex={-1}>Which expression fits?</h2>{learner.history && <p className="lesson-history"><strong>Previously practised</strong><span>{learner.history.attemptCount} attempt{learner.history.attemptCount === 1 ? "" : "s"} on the first question</span></p>}<div className="activity-stack">{practice.map(item => <Choice key={item.id} {...item} onComplete={complete} />)}</div></section>}

    {step === 3 && <section className="lesson-stage"><p className="learn-preview-kicker">4 · Listen</p><h2 ref={headingRef} tabIndex={-1}>Hear the difference</h2><div className="activity-stack">{listening.map(([number, audio, options]) => <Listening key={number} id={`item.a1.u01.l01.listening.${number}`} audio={audio} options={options} onComplete={complete} />)}</div></section>}

    {step === 4 && <section className="lesson-stage"><p className="learn-preview-kicker">5 · Build and retrieve</p><h2 ref={headingRef} tabIndex={-1}>Bring the expressions back from memory</h2><div className="activity-stack">{builders.map(item => <Builder key={item[0]} item={item} onComplete={complete} />)}</div><div className="delayed-recall"><h3>No-hint recall</h3><p>You met this expression earlier. Retrieve it without returning to the phrase guide. Accents are encouraged but not required yet.</p><TypedRecallRenderer activityId="activity.a1.u01.l01.delayed" itemId="item.a1.u01.l01.delayed" prompt="Type ‘See you tomorrow!’ in French." answers={["À demain !"]} policy={{ accents: "forgiving", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete("item.a1.u01.l01.delayed", String(envelope.response), evaluation.outcome === "correct")} /></div><div className="transfer-challenge"><p className="learn-preview-kicker">New setting</p><h3>You leave a café at 8 p.m. What fits?</h3><Choice id="item.a1.u01.l01.transfer" prompt="Choose your final words to the server." options={["Bonsoir !", "Bonne soirée !", "Bonjour !"]} answer="Bonne soirée !" feedback={{ "Bonsoir !": "Bonsoir greets someone when arriving.", "Bonne soirée !": "Bonne soirée is the evening leaving wish." }} onComplete={complete} /></div></section>}

    {step === 5 && <section className="lesson-stage"><p className="learn-preview-kicker">6 · Speak</p><h2 ref={headingRef} tabIndex={-1}>Make the phrases yours</h2><div className="activity-stack"><Speaking id="item.a1.u01.l01.speaking.001" prompt="It is morning. Greet your teacher." model="Bonjour !" onComplete={complete} /><Speaking id="item.a1.u01.l01.speaking.002" prompt="You are leaving and will return tomorrow." model="Au revoir ! À demain !" onComplete={complete} /></div></section>}

    {step === 6 && <section className="lesson-stage lesson-check" key={exitRound}><p className="learn-preview-kicker">7 · Check</p><h2 ref={headingRef} tabIndex={-1}>Can you use it without hints?</h2><p>Pass with 3 of 4, including the typed recall.</p><Listening id="item.a1.u01.l01.exit.listening" audio="Bonsoir !" options={["Bonjour !", "Bonsoir !", "Bonne soirée !"]} assessment onComplete={exitComplete} /><Choice id="item.a1.u01.l01.exit.arrival" prompt="It is daytime. Choose a polite arrival." options={["Bonjour !", "Salut !", "Au revoir !"]} answer="Bonjour !" onComplete={exitComplete} /><Choice id="item.a1.u01.l01.exit.farewell" prompt="You leave during the day and wish someone well." options={["Bonne journée !", "Bonjour !", "Bonsoir !"]} answer="Bonne journée !" onComplete={exitComplete} /><TypedRecallRenderer activityId="activity.a1.u01.l01.exit" itemId="item.a1.u01.l01.exit.typed" prompt="Type ‘See you soon!’ in French." answers={["À bientôt !"]} policy={{ accents: "required", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => exitComplete("item.a1.u01.l01.exit.typed", String(envelope.response), evaluation.outcome === "correct")} />{Object.keys(exitResults).length === 4 && <Button onClick={() => void checkExit()}>Check my lesson result</Button>}{exitStatus === "failed" && <div className="remediation"><Feedback title="One short review before retrying" tone="error">Review arrival versus leaving wishes, then retry this four-item check. Your earlier attempt remains saved.</Feedback><div className="phrase-contrast"><span><strong>Bonjour / Bonsoir</strong><small>arriving</small></span><span><strong>Bonne journée / Bonne soirée</strong><small>leaving wishes</small></span></div><Button onClick={() => { setExitRound(value => value + 1); setExitResults({}); setExitStatus("idle"); }}>Retry lesson check</Button></div>}</section>}

    {step === 7 && <section className="lesson-stage lesson-summary"><p className="lesson-celebration" aria-hidden="true">✓</p><p className="learn-preview-kicker">Lesson complete</p><h2 ref={headingRef} tabIndex={-1}>You can now enter and leave a simple French interaction</h2><p>You can choose greetings by time of day and distinguish them from leaving wishes.</p><div className="summary-grid"><Card title="Your strengths"><p>{Object.values(exitResults).filter(Boolean).length || 4} successful check items, including recall.</p></Card><Card title="Keep available"><p>Listen once more to <strong>bonjour / bonne journée</strong> before your next session.</p></Card></div><div className="lesson-inline-actions"><Button onClick={() => void move(1)}>Practise this lesson again</Button><Button variant="secondary" disabled>Next: Names and alphabet</Button></div></section>}

    {step < 7 && <nav className="lesson-navigation" aria-label="Lesson navigation">{step > 0 ? <Button variant="secondary" onClick={() => void move(step - 1)}>← Previous</Button> : <span />}{step < 6 && <Button disabled={step >= furthestStep && !stepRequirements[step]} onClick={() => void move(step + 1)}>Continue to {steps[step + 1]} →</Button>}</nav>}
  </article>;
}
