import { useEffect, useRef, useState } from "react";
import { AudioTextSelectRenderer, MeaningSelectRenderer, SentenceBuildRenderer, TypedRecallRenderer } from "../activities/registry";
import { AudioControl, Button, Card, Feedback, Link, Progress } from "../design-system";
import { useGuestLearner } from "../features/learner/useGuestLearner";
import { speak } from "../speak";

const lessonId = "lesson.fr-general.a1.first-contact.names-alphabet";
const steps = ["Warm-up", "Meet", "Alphabet", "Contrast", "Spell", "Use", "Check", "Complete"];
const alphabetGroups = [
  ["A", "B", "C", "D", "E", "F"], ["G", "H", "I", "J", "K", "L", "M"],
  ["N", "O", "P", "Q", "R", "S", "T"], ["U", "V", "W", "X", "Y", "Z"],
] as const;
const letterCues: Record<string, string> = { A: "ah", B: "bay", C: "say", D: "day", E: "uh", F: "eff", G: "zhay", H: "ahsh", I: "ee", J: "zhee", K: "kah", L: "ell", M: "emm", N: "enn", O: "oh", P: "pay", Q: "kü", R: "French air", S: "ess", T: "tay", U: "French u", V: "vay", W: "double-vay", X: "eeks", Y: "ee-grek", Z: "zed" };
const contrasts = [
  ["G", ["G", "J"]], ["I", ["E", "I"]], ["P", ["B", "P"]], ["T", ["D", "T"]], ["U", ["Q", "U"]], ["N", ["M", "N"]], ["Z", ["C", "Z"]],
] as const;
const names = [{ name: "Léa", spelling: "L – É – A" }, { name: "Amir", spelling: "A – M – I – R" }, { name: "Sofia", spelling: "S – O – F – I – A" }, { name: "Hugo", spelling: "H – U – G – O" }];
type Complete = (id: string, response: string, correct: boolean) => Promise<void>;

function Choice({ id, prompt, options, answer, onComplete }: { id: string; prompt: string; options: readonly string[]; answer: string; onComplete: Complete }) {
  return <MeaningSelectRenderer activityId={id.replace("item", "activity").replace(/\.\w+$/, "")} itemId={id} prompt={prompt} options={options} answer={answer} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} />;
}
function LetterChoice({ id, letter, options, onComplete, assessment = false }: { id: string; letter: string; options: readonly string[]; onComplete: Complete; assessment?: boolean }) {
  return <div className="listening-activity"><strong>Which letter do you hear?</strong><AudioTextSelectRenderer activityId="activity.a1.u01.l02.letters" itemId={id} audio={letter} options={options} answer={letter} assessment={assessment} feedback={{ [letter]: `That is the French letter ${letter}.` }} onSubmit={({ envelope, evaluation }) => onComplete(id, String(envelope.response), evaluation.outcome === "correct")} /></div>;
}

export default function NamesAlphabetLesson() {
  const learner = useGuestLearner(lessonId); const sessionId = useRef<string | undefined>(undefined); const hydrated = useRef(false); const headingRef = useRef<HTMLHeadingElement>(null);
  const [step, setStep] = useState(0); const [furthestStep, setFurthestStep] = useState(0); const [completed, setCompleted] = useState<Set<string>>(new Set()); const [group, setGroup] = useState(0); const [practisedGroups, setPractisedGroups] = useState<Set<number>>(new Set()); const [transcript, setTranscript] = useState(false); const [exit, setExit] = useState<Record<string, boolean>>({}); const [round, setRound] = useState(1); const [saveError, setSaveError] = useState<string>();
  useEffect(() => { if (!learner.loading && !hydrated.current) { hydrated.current = true; const saved = Math.min(learner.progress?.currentStep ?? 0, 7); setStep(saved); setFurthestStep(Math.min(learner.progress?.furthestStep ?? saved, 7)); } }, [learner.loading, learner.progress]);
  useEffect(() => { headingRef.current?.focus(); }, [step]);
  useEffect(() => () => { if (sessionId.current) void learner.repository.endSession(sessionId.current); }, [learner.repository]);
  const complete: Complete = async (itemId, response, correct) => { if (correct) setCompleted(current => new Set(current).add(itemId)); if (!learner.enrollment) return; try { if (!sessionId.current) sessionId.current = (await learner.repository.startSession(lessonId, "deep_link")).id; await learner.repository.submitAttempt({ learnerId: learner.enrollment.learnerId, enrollmentId: learner.enrollment.id, sessionId: sessionId.current, lessonId, activityId: itemId.replace("item", "activity").replace(/\.\w+$/, ""), itemId, response, correct, idempotencyKey: crypto.randomUUID() }); await learner.refresh(); setSaveError(undefined); } catch { setSaveError("Progress could not be saved. You can continue this session."); } };
  const exitComplete: Complete = async (id, response, correct) => { setExit(current => ({ ...current, [id]: correct })); await complete(id, response, correct); };
  const move = async (next: number) => { setStep(next); setFurthestStep(current => Math.max(current, next)); if (learner.enrollment) { try { await learner.repository.saveLessonPosition(lessonId, next); await learner.refresh(); } catch { setSaveError("Your lesson position could not be saved."); } } };
  const requirements = [completed.has("item.a1.u01.l02.warmup.001") && completed.has("item.a1.u01.l02.warmup.002"), completed.has("item.a1.u01.l02.notice"), completed.has("item.a1.u01.l02.alphabet"), contrasts.every((_, i) => completed.has(`item.a1.u01.l02.contrast.${i}`)), completed.has("item.a1.u01.l02.name.lea") && completed.has("item.a1.u01.l02.name.amir"), completed.has("item.a1.u01.l02.phrase.build") && completed.has("item.a1.u01.l02.phrase.recall"), false, false];
  const check = async () => { const values = Object.values(exit); if (values.length === 4 && values.filter(Boolean).length >= 3 && exit["item.a1.u01.l02.exit.name"]) { if (learner.enrollment) await learner.repository.completeLesson(lessonId); await move(7); } };
  if (learner.loading) return <p role="status">Loading Lesson 2…</p>;
  return <article className="lesson-flow lesson-player names-alphabet-lesson">
    <header className="lesson-flow__header"><Link to="/learn/a1/unit/first-contact">← Unit 1 outline</Link><p className="learn-preview-kicker">Unit 1 · Lesson 2 · {steps[step]}</p><h1>Names and alphabet</h1><p className="page-sub">I can recognize French letter names and spell a first name.</p><Progress label="Lesson progress" value={step} max={7} /><ol className="lesson-stepper" aria-label="Lesson steps">{steps.map((label, index) => <li key={label} className={index === step ? "is-current" : index < step ? "is-done" : ""}><span>{index + 1}</span>{label}</li>)}</ol>{saveError && <Feedback title="Save issue" tone="error">{saveError}</Feedback>}</header>

    {step === 0 && <section className="lesson-stage lesson-two-warmup"><div className="lesson-stage-intro"><p className="learn-preview-kicker">1 · Quick retrieval</p><h2 ref={headingRef} tabIndex={-1}>Bring back two greetings</h2><p>A short review helps Lesson 1 language stay available before you learn something new.</p></div><div className="contrast-grid"><Choice id="item.a1.u01.l02.warmup.001" prompt="You arrive during the day. What do you say?" options={["Bonjour !", "Au revoir !"]} answer="Bonjour !" onComplete={complete} /><Choice id="item.a1.u01.l02.warmup.002" prompt="You leave and will return tomorrow. What do you say?" options={["À demain !", "Bonsoir !"]} answer="À demain !" onComplete={complete} /></div></section>}
    {step === 1 && <section className="lesson-stage lesson-scene lesson-two-scene"><img src="/images/course/a1/unit-01/names-alphabet-reception-v1.png" alt="Ira gives her name at a language-school reception desk while Sofia listens nearby." /><div className="lesson-scene__copy"><div className="lesson-stage-intro"><p className="learn-preview-kicker">2 · Meet the language</p><h2 ref={headingRef} tabIndex={-1}>A name at the class desk</h2><p>Listen first. What information does the receptionist ask Ira to give after her name?</p></div><AudioControl label="Play reception dialogue" onPlay={() => speak("Bonjour. Votre prénom ? Ira. Comment ça s'écrit ? I – R – A. Merci.")} onPlaySlow={() => speak("Bonjour. Votre prénom ? Ira. Comment ça s'écrit ? I – R – A. Merci.", { rate: 0.75 })} /><Choice id="item.a1.u01.l02.notice" prompt="What does Ira provide after her name?" options={["Its spelling", "Her address", "Her age"]} answer="Its spelling" onComplete={complete} /><div className="lesson-inline-actions"><Button variant="secondary" onClick={() => setTranscript(value => !value)}>{transcript ? "Hide transcript" : "Show transcript"}</Button></div>{transcript && <div className="dialogue"><div><strong>Receptionist</strong><span><b>Bonjour. Votre prénom ?</b><small>Hello. Your first name?</small></span></div><div><strong>Ira</strong><span><b>Ira.</b><small>Ira.</small></span></div><div><strong>Receptionist</strong><span><b>Comment ça s’écrit ?</b><small>How is that spelled?</small></span></div><div><strong>Ira</strong><span><b>I – R – A.</b><small>I – R – A.</small></span></div></div>}<Card title="Useful chunk"><p><strong>Comment ça s’écrit ?</strong> means “How is that spelled?” Learn the whole question as one useful chunk.</p></Card></div></section>}
    {step === 2 && <section className="lesson-stage"><p className="learn-preview-kicker">3 · Explore the alphabet</p><h2 ref={headingRef} tabIndex={-1}>Same letters, different names</h2><p>French uses the same 26 basic letters as English. The cues are temporary listening aids—not exact pronunciations.</p><div className="lesson-tabs">{alphabetGroups.map((_, index) => <Button key={index} variant={group === index ? "primary" : "secondary"} onClick={() => setGroup(index)}>Group {index + 1}{practisedGroups.has(index) ? " ✓" : ""}</Button>)}</div><div className="phrase-guide alphabet-grid">{alphabetGroups[group].map(letter => <button key={letter} onClick={() => speak(letter)}><span>🔊</span><strong>{letter}</strong><small>{letterCues[letter]}</small></button>)}</div><Button onClick={() => { const next = new Set(practisedGroups).add(group); setPractisedGroups(next); if (next.size === 4) void complete("item.a1.u01.l02.alphabet", "four-groups", true); setGroup(current => Math.min(current + 1, 3)); }}>{practisedGroups.has(group) ? "Practised ✓" : "I practised this group"}</Button><Card title="Marks matter"><p><strong>é, è, ê, ë, à, ç, î, ô</strong> are not extra letters. In a person’s name, preserve their exact spelling.</p></Card></section>}
    {step === 3 && <section className="lesson-stage"><p className="learn-preview-kicker">4 · Hear the contrast</p><h2 ref={headingRef} tabIndex={-1}>Letters learners often confuse</h2><div className="activity-stack">{contrasts.map(([letter, options], index) => <LetterChoice key={index} id={`item.a1.u01.l02.contrast.${index}`} letter={letter} options={options} onComplete={complete} />)}</div></section>}
    {step === 4 && <section className="lesson-stage"><p className="learn-preview-kicker">5 · Spell names</p><h2 ref={headingRef} tabIndex={-1}>Turn letter sequences into names</h2><div className="summary-grid">{names.map(item => <Card key={item.name} title={item.name}><AudioControl label={`Hear ${item.name} spelled`} onPlay={() => speak(item.spelling.replaceAll(" – ", ", "))} onPlaySlow={() => speak(item.spelling.replaceAll(" – ", ", "), { rate: 0.7 })} /><p>{item.spelling}</p></Card>)}</div><div className="activity-stack"><TypedRecallRenderer activityId="activity.a1.u01.l02.names" itemId="item.a1.u01.l02.name.lea" prompt="You hear L – É – A. Type the name." answers={["Léa"]} policy={{ accents: "required", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete("item.a1.u01.l02.name.lea", String(envelope.response), evaluation.outcome === "correct")} /><TypedRecallRenderer activityId="activity.a1.u01.l02.names" itemId="item.a1.u01.l02.name.amir" prompt="You hear A – M – I – R. Type the name." answers={["Amir"]} policy={{ accents: "required", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete("item.a1.u01.l02.name.amir", String(envelope.response), evaluation.outcome === "correct")} /></div></section>}
    {step === 5 && <section className="lesson-stage"><p className="learn-preview-kicker">6 · Use the phrases</p><h2 ref={headingRef} tabIndex={-1}>Ask and answer about spelling</h2><div className="activity-stack"><SentenceBuildRenderer activityId="activity.a1.u01.l02.phrase" itemId="item.a1.u01.l02.phrase.build" prompt="Build ‘It is spelled…’" tokens={["s’écrit", "…", "Ça"]} answer="Ça s’écrit …" onSubmit={({ envelope, evaluation }) => complete("item.a1.u01.l02.phrase.build", String(envelope.response), evaluation.outcome === "correct")} /><TypedRecallRenderer activityId="activity.a1.u01.l02.phrase" itemId="item.a1.u01.l02.phrase.recall" prompt="Type ‘How is that spelled?’ in French." answers={["Comment ça s’écrit ?", "Comment ça s'écrit ?"]} policy={{ accents: "forgiving", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => complete("item.a1.u01.l02.phrase.recall", String(envelope.response), evaluation.outcome === "correct")} /></div><aside className="role-play"><strong>Optional speaking</strong><p>Choose any name. Say: <em>Ça s’écrit…</em>, then spell it with French letter names.</p><AudioControl label="Hear the speaking model" onPlay={() => speak("Ça s'écrit I, R, A.")} onPlaySlow={() => speak("Ça s'écrit I, R, A.", { rate: 0.75 })} /></aside></section>}
    {step === 6 && <section className="lesson-stage lesson-check" key={round}><p className="learn-preview-kicker">7 · Check</p><h2 ref={headingRef} tabIndex={-1}>Can you hear and spell without hints?</h2><p>Pass 3 of 4, including the name.</p><LetterChoice id="item.a1.u01.l02.exit.g" letter="G" options={["G", "J"]} assessment onComplete={exitComplete} /><LetterChoice id="item.a1.u01.l02.exit.u" letter="U" options={["Q", "U"]} assessment onComplete={exitComplete} /><Choice id="item.a1.u01.l02.exit.phrase" prompt="Choose ‘How is that spelled?’" options={["Comment ça s’écrit ?", "Votre prénom ?", "Ça s’écrit…"]} answer="Comment ça s’écrit ?" onComplete={exitComplete} /><TypedRecallRenderer activityId="activity.a1.u01.l02.exit" itemId="item.a1.u01.l02.exit.name" prompt="You hear S – O – F – I – A. Type the name." answers={["Sofia"]} policy={{ accents: "required", punctuation: "optional" }} onSubmit={({ envelope, evaluation }) => exitComplete("item.a1.u01.l02.exit.name", String(envelope.response), evaluation.outcome === "correct")} />{Object.keys(exit).length === 4 && <Button onClick={() => void check()}>Check my lesson result</Button>}{Object.keys(exit).length === 4 && !(Object.values(exit).filter(Boolean).length >= 3 && exit["item.a1.u01.l02.exit.name"]) && <div className="remediation"><Feedback title="Review and retry" tone="error">Listen once more to G/J and Q/U, and keep the letters in the name’s original order.</Feedback><Button onClick={() => { setRound(value => value + 1); setExit({}); }}>Retry lesson check</Button></div>}</section>}
    {step === 7 && <section className="lesson-stage lesson-summary"><p className="lesson-celebration" aria-hidden="true">✓</p><p className="learn-preview-kicker">Lesson complete</p><h2 ref={headingRef} tabIndex={-1}>You can recognize French letters and spell a name</h2><p>You can ask how something is spelled, hear important letter contrasts, and keep a name’s spelling in order.</p><div className="lesson-inline-actions"><Button onClick={() => void move(0)}>Practise again</Button><Button variant="secondary" disabled>Next: Core sound map</Button></div></section>}
    {step < 7 && <nav className="lesson-navigation" aria-label="Lesson navigation">{step > 0 ? <Button variant="secondary" onClick={() => void move(step - 1)}>← Previous</Button> : <span />}{step < 6 && <Button disabled={step >= furthestStep && !requirements[step]} onClick={() => void move(step + 1)}>Continue to {steps[step + 1]} →</Button>}</nav>}
  </article>;
}
