// ============================================================
//  commonWords.js — the ~100 most common French words
// ------------------------------------------------------------
//  Roughly frequency-ordered. Learning these gives you the
//  biggest understanding boost for the least effort.
//    fr   : the French word
//    en   : English meaning
//    type : grammar category (helps you sort/understand)
// ============================================================
export const commonWords = [
  { fr: "le", en: "the (m)", type: "article" },
  { fr: "la", en: "the (f)", type: "article" },
  { fr: "les", en: "the (plural)", type: "article" },
  { fr: "un", en: "a / one (m)", type: "article" },
  { fr: "une", en: "a / one (f)", type: "article" },
  { fr: "de", en: "of / from", type: "preposition" },
  { fr: "et", en: "and", type: "conjunction" },
  { fr: "à", en: "to / at", type: "preposition" },
  { fr: "être", en: "to be", type: "verb" },
  { fr: "avoir", en: "to have", type: "verb" },
  { fr: "je", en: "I", type: "pronoun" },
  { fr: "tu", en: "you (informal)", type: "pronoun" },
  { fr: "il", en: "he / it", type: "pronoun" },
  { fr: "elle", en: "she / it", type: "pronoun" },
  { fr: "nous", en: "we", type: "pronoun" },
  { fr: "vous", en: "you (formal/plural)", type: "pronoun" },
  { fr: "ils", en: "they (m)", type: "pronoun" },
  { fr: "elles", en: "they (f)", type: "pronoun" },
  { fr: "on", en: "one / we", type: "pronoun" },
  { fr: "ne", en: "not (part 1)", type: "negation" },
  { fr: "pas", en: "not (part 2)", type: "negation" },
  { fr: "que", en: "that / which", type: "conjunction" },
  { fr: "qui", en: "who / which", type: "pronoun" },
  { fr: "ce", en: "this / it", type: "pronoun" },
  { fr: "dans", en: "in", type: "preposition" },
  { fr: "en", en: "in / of it", type: "preposition" },
  { fr: "du", en: "of the (m)", type: "article" },
  { fr: "des", en: "some / of the", type: "article" },
  { fr: "pour", en: "for", type: "preposition" },
  { fr: "par", en: "by / through", type: "preposition" },
  { fr: "sur", en: "on", type: "preposition" },
  { fr: "avec", en: "with", type: "preposition" },
  { fr: "sans", en: "without", type: "preposition" },
  { fr: "sous", en: "under", type: "preposition" },
  { fr: "faire", en: "to do / make", type: "verb" },
  { fr: "dire", en: "to say", type: "verb" },
  { fr: "pouvoir", en: "to be able / can", type: "verb" },
  { fr: "aller", en: "to go", type: "verb" },
  { fr: "voir", en: "to see", type: "verb" },
  { fr: "vouloir", en: "to want", type: "verb" },
  { fr: "venir", en: "to come", type: "verb" },
  { fr: "savoir", en: "to know", type: "verb" },
  { fr: "prendre", en: "to take", type: "verb" },
  { fr: "devoir", en: "to have to / must", type: "verb" },
  { fr: "mettre", en: "to put", type: "verb" },
  { fr: "donner", en: "to give", type: "verb" },
  { fr: "parler", en: "to speak", type: "verb" },
  { fr: "aimer", en: "to like / love", type: "verb" },
  { fr: "penser", en: "to think", type: "verb" },
  { fr: "trouver", en: "to find", type: "verb" },
  { fr: "mon", en: "my (m)", type: "possessive" },
  { fr: "ma", en: "my (f)", type: "possessive" },
  { fr: "son", en: "his / her (m)", type: "possessive" },
  { fr: "leur", en: "their", type: "possessive" },
  { fr: "me", en: "me", type: "pronoun" },
  { fr: "lui", en: "him / to him", type: "pronoun" },
  { fr: "y", en: "there", type: "pronoun" },
  { fr: "mais", en: "but", type: "conjunction" },
  { fr: "ou", en: "or", type: "conjunction" },
  { fr: "où", en: "where", type: "adverb" },
  { fr: "si", en: "if / so", type: "conjunction" },
  { fr: "comme", en: "like / as", type: "conjunction" },
  { fr: "parce que", en: "because", type: "conjunction" },
  { fr: "donc", en: "so / therefore", type: "conjunction" },
  { fr: "quand", en: "when", type: "adverb" },
  { fr: "comment", en: "how", type: "adverb" },
  { fr: "pourquoi", en: "why", type: "adverb" },
  { fr: "plus", en: "more", type: "adverb" },
  { fr: "moins", en: "less", type: "adverb" },
  { fr: "très", en: "very", type: "adverb" },
  { fr: "bien", en: "well", type: "adverb" },
  { fr: "aussi", en: "also / too", type: "adverb" },
  { fr: "beaucoup", en: "a lot", type: "adverb" },
  { fr: "toujours", en: "always", type: "adverb" },
  { fr: "jamais", en: "never", type: "adverb" },
  { fr: "encore", en: "again / still", type: "adverb" },
  { fr: "déjà", en: "already", type: "adverb" },
  { fr: "ici", en: "here", type: "adverb" },
  { fr: "là", en: "there", type: "adverb" },
  { fr: "maintenant", en: "now", type: "adverb" },
  { fr: "aujourd'hui", en: "today", type: "adverb" },
  { fr: "demain", en: "tomorrow", type: "adverb" },
  { fr: "hier", en: "yesterday", type: "adverb" },
  { fr: "tout", en: "all / everything", type: "adjective" },
  { fr: "grand", en: "big / tall", type: "adjective" },
  { fr: "petit", en: "small", type: "adjective" },
  { fr: "bon", en: "good", type: "adjective" },
  { fr: "nouveau", en: "new", type: "adjective" },
  { fr: "même", en: "same / even", type: "adjective" },
  { fr: "autre", en: "other", type: "adjective" },
  { fr: "beau", en: "beautiful", type: "adjective" },
  { fr: "chose", en: "thing", type: "noun" },
  { fr: "temps", en: "time / weather", type: "noun" },
  { fr: "jour", en: "day", type: "noun" },
  { fr: "homme", en: "man", type: "noun" },
  { fr: "femme", en: "woman", type: "noun" },
  { fr: "enfant", en: "child", type: "noun" },
  { fr: "vie", en: "life", type: "noun" },
  { fr: "monde", en: "world / people", type: "noun" },
  { fr: "oui", en: "yes", type: "word" },
  { fr: "non", en: "no", type: "word" },
];

// The list of unique word types (for the filter buttons).
export const wordTypes = [...new Set(commonWords.map((w) => w.type))];
