import type { Attempt, DraftResponse, Enrollment, Evaluation, GuestProfile, LearnerExport, LessonProgress, LearningGoal, LearningSession } from "../../domain/learner";
import type { AttemptInput, LearnerRepository } from "../../repositories/learner/LearnerRepository";
const stores = ["metadata","profiles","goals","enrollments","sessions","attempts","evaluations","drafts","lesson_progress","outbox","tombstones"];
const req = <T>(r: IDBRequest<T>) => new Promise<T>((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const done = (t: IDBTransaction) => new Promise<void>((ok,no)=>{t.oncomplete=()=>ok();t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)});
export class IndexedDbLearnerRepository implements LearnerRepository {
 constructor(private name="parlo-learner", private project=()=>{}){}
 private open(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open(this.name,1);r.onupgradeneeded=()=>{for(const s of stores)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:s==="metadata"?"key":s==="profiles"?"learnerId":s==="lesson_progress"?"lessonId":"id"});const a=r.transaction?.objectStore("attempts");if(a&&!a.indexNames.contains("idempotencyKey"))a.createIndex("idempotencyKey","idempotencyKey",{unique:true})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});}
 async getActiveEnrollment(){const d=await this.open(),t=d.transaction(["metadata","enrollments"]),m=await req(t.objectStore("metadata").get("activeEnrollmentId")) as {value:string}|undefined,e=m?await req(t.objectStore("enrollments").get(m.value)) as Enrollment:undefined;d.close();return e}
 async startA1(){const old=await this.getActiveEnrollment(),d=await this.open();if(old){const t=d.transaction(["profiles","goals"]),profile=await req(t.objectStore("profiles").get(old.learnerId)) as GuestProfile,goals=await req(t.objectStore("goals").getAll()) as LearningGoal[];d.close();return{profile,enrollment:old,goal:goals[0]}}const now=new Date().toISOString(),learnerId=`learner_${crypto.randomUUID()}`,profile:GuestProfile={learnerId,mode:"guest",createdAt:now,interfaceLocale:"en",targetLanguage:"fr"},enrollment:Enrollment={id:`enrollment_${crypto.randomUUID()}`,learnerId,courseId:"course.fr-general",levelId:"level.fr-general.a1",status:"active",startedAt:now,selectedStartUnitId:"unit.fr-general.a1.first-contact"},goal:LearningGoal={id:`goal_${crypto.randomUUID()}`,learnerId,enrollmentId:enrollment.id,goalType:"general_french",targetLevel:"a1",dailyMinutes:15,studyDays:["monday","tuesday","wednesday","thursday","friday"],status:"active"},t=d.transaction(["profiles","goals","enrollments","metadata"],"readwrite");t.objectStore("profiles").put(profile);t.objectStore("goals").put(goal);t.objectStore("enrollments").put(enrollment);t.objectStore("metadata").put({key:"activeEnrollmentId",value:enrollment.id});await done(t);d.close();return{profile,enrollment,goal}}
 async startSession(lessonId:string,entryPoint:LearningSession["entryPoint"]){const e=await this.getActiveEnrollment();if(!e)throw Error("Start A1 first");const s:LearningSession={id:`session_${crypto.randomUUID()}`,learnerId:e.learnerId,enrollmentId:e.id,lessonId,entryPoint,startedAt:new Date().toISOString(),endedAt:null},d=await this.open(),t=d.transaction("sessions","readwrite");t.objectStore("sessions").add(s);await done(t);d.close();return s}
 async endSession(id:string){const d=await this.open(),t=d.transaction("sessions","readwrite"),o=t.objectStore("sessions"),s=await req(o.get(id)) as LearningSession|undefined;if(s)o.put({...s,endedAt:new Date().toISOString()});await done(t);d.close()}
 async submitAttempt(i:AttemptInput){const d=await this.open(),prior=await req(d.transaction("attempts").objectStore("attempts").index("idempotencyKey").get(i.idempotencyKey)) as Attempt|undefined;if(prior){d.close();return{attempt:prior,progress:(await this.getLessonProgress(i.lessonId))!,duplicate:true}}const now=new Date().toISOString(),{correct,lessonId,...rest}=i,a:Attempt={id:`attempt_${crypto.randomUUID()}`,submittedAt:now,...rest},e:Evaluation={id:`evaluation_${crypto.randomUUID()}`,attemptId:a.id,revision:1,evaluator:"deterministic",outcome:correct?"correct":"incorrect",score:correct?1:0,createdAt:now},old=await this.getLessonProgress(lessonId);let p:LessonProgress={lessonId,learnerId:i.learnerId,status:"in_progress",attemptCount:(old?.attemptCount??0)+1,correctCount:(old?.correctCount??0)+(correct?1:0),updatedAt:now,recalculationRequired:false};try{this.project()}catch{p={...p,recalculationRequired:true}}const t=d.transaction(["attempts","evaluations","lesson_progress","outbox","drafts"],"readwrite");t.objectStore("attempts").add(a);t.objectStore("evaluations").add(e);t.objectStore("lesson_progress").put(p);t.objectStore("outbox").put({id:`outbox_${a.id}`,attemptId:a.id});t.objectStore("drafts").delete(i.itemId);await done(t);d.close();return{attempt:a,progress:p,duplicate:false}}
 async getLessonProgress(id:string){const d=await this.open(),v=await req(d.transaction("lesson_progress").objectStore("lesson_progress").get(id)) as LessonProgress|undefined;d.close();return v}
 async saveDraft(itemId:string,value:string){const e=await this.getActiveEnrollment();if(!e)throw Error("No enrollment");const v:DraftResponse={id:itemId,itemId,learnerId:e.learnerId,value,updatedAt:new Date().toISOString()},d=await this.open(),t=d.transaction("drafts","readwrite");t.objectStore("drafts").put(v);await done(t);d.close();return v}
 async getDraft(id:string){const d=await this.open(),v=await req(d.transaction("drafts").objectStore("drafts").get(id)) as DraftResponse|undefined;d.close();return v}
 async clearDraft(id:string){const d=await this.open(),t=d.transaction("drafts","readwrite");t.objectStore("drafts").delete(id);await done(t);d.close()}
 async exportProgress(){const d=await this.open(),all=<T>(s:string)=>req(d.transaction(s).objectStore(s).getAll()) as Promise<T[]>,profiles=await all<GuestProfile>("profiles");const v:LearnerExport={format:"parlo-guest-progress",version:1,exportedAt:new Date().toISOString(),profile:profiles[0],goals:await all("goals"),enrollments:await all("enrollments"),sessions:await all("sessions"),attempts:await all("attempts"),evaluations:await all("evaluations"),lessonProgress:await all("lesson_progress")};d.close();return v}
 async deleteLocalProgress(){const d=await this.open(),t=d.transaction(stores,"readwrite");for(const s of stores)t.objectStore(s).clear();await done(t);d.close()}
}
